### ISSUE TITLE
Litecoin restoring with 12 word mnemonic broken

### ISSUE THREAD

**Issue by tuxpizza** [cake-tech/cake_wallet#1001]
Recently I tried restoring a Litecoin wallet by using the 12 word mnemonic (I confirmed it is correct mnemonic with 12 words) and it gives me an error, saying the "Bitcoin mnemonic has incorrect format."

However restoring a 24 word mnemonic works fine.

Version: Cake Wallet 4.6.7
GrapheneOS (Android 13)
Pixel 7

![image](https://github.com/cake-tech/cake_wallet/assets/84710786/c5fd10da-91ed-438d-9ddd-6ffa03064255)

I didn't see anything useful in Logcat while reproducing this issue.

**Comment by KlaudAda28** [comment]
Have you able to resolved your issues? @tuxpizza

**Comment by DaLiV** [comment]
seems in use somehow "modified code" that breaks the BIP standarts ... 
has tried some test vectors from :
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
both lenghts 12 and 24 was unsucessfull .

**Comment by DaLiV** [comment]
that bug also breaks possibility to migrate from other wallets 
"cake" uses non-standart "recovery mnemonic" at least for LTC !!! ...
any chances that this will be got onto normal rails ?

**Comment by tuxpizza** [comment]
> that bug also breaks possibility to migrate from other wallets "cake" uses non-standart "recovery mnemonic" at least for LTC !!! ... any chances that this will be got onto normal rails ?

Looking into this!

**Comment by tuxpizza** [comment]
This is actually due to the fact we use Electrum and the regular/BIP-39 seeds are incompatible with Electrum wallets

**Comment by DaLiV** [comment]
That resolves not an isue ... but simple make announce "we donät want to fix" and "we are totallz incompatible" to anz wallet on the net.
can suggest another way - options (on export and on import)
(*) Use regular BIP-39
(*) Use Electrum Mnemonic
