### ISSUE TITLE
[minor] Swapping wallets (BTC then XMR) still shows BTC receive QR code

### ISSUE THREAD

**Issue by ronohara** [cake-tech/cake_wallet#1046]
Desktop Linux Cake wallet .. 4.8.0  - Linux Mint 22.2 (Mate)

I have two wallets created. One is XMR the other BTC.

If the BTC wallet is open, and you press Receive to get the receive QR code, then swap wallets to the XMR wallet, the QR code for receiving BTC is still displayed.

Annoying, but not critical - and slightly confusing to people who may not realise the displayed QR code is not for an XMR address.

**Comment by OmarHatem28** [comment]
Closed by #1068 will be out in the next release, thanks for the feedback
