### ISSUE TITLE
Feature request - APK

### ISSUE THREAD

**Issue by kn0wmad** [cake-tech/cake_wallet#105]
Good day, would it be possible to have an APK available, perhaps on github and/or your website.  Adding to FDroid would also be awesome

**Comment by nahuhh** [comment]
Came here to request f-droid inclusion as well. Nice to see we're 2/2 so far.

**Comment by mezzazon** [comment]
https://github.com/cake-tech/cake_wallet/releases/tag/4.1.4

**Comment by mezzazon** [comment]
Working on adding to fdroid too, but it make some constrains for us which we need to avoid.

**Comment by kn0wmad** [comment]
> https://github.com/cake-tech/cake_wallet/releases/tag/4.1.4

Awesome, thank you team :)

I'm happy for this to be closed, unless you want to leave it open for fdroid support

**Comment by tannerdsilva** [comment]
This ticket is being closed due to the title. New issue will be created for fdroid support.
