### ISSUE TITLE
The Android app-icon is not centered

### ISSUE THREAD

**Issue by K4LCIFER** [cake-tech/cake_wallet#1053]
![Screenshot_20230819-145511_1](https://github.com/cake-tech/cake_wallet/assets/7829231/c4342365-e34f-4742-844e-7c3b57a8b9e5)

As shown in the above picture, the icon logo is not centered.

**Comment by SamsungGalaxyPlayer** [comment]
Is this for the f-droid store, or something else?

**Comment by K4LCIFER** [comment]
> Is this for the f-droid store, or something else?

It's installed through the Google Play store.

- Android 14 beta
- Google Pixel 6
