### ISSUE TITLE
Accessibility: unlabeled or unspoken buttons with talkback

### ISSUE THREAD

**Issue by shortwavesurfer2009** [cake-tech/cake_wallet#1061]
The following buttons are either unlabeled or totally unspoken when using talkback.
![Screenshot_20230826-091344_Monero com](https://github.com/cake-tech/cake_wallet/assets/116814522/0497eba1-a0f6-4671-882b-912903da391e)
![Screenshot_20230826-091555_Monero com](https://github.com/cake-tech/cake_wallet/assets/116814522/29ea7c2a-6c05-4625-b1dc-ee0c53c43d17)
![Screenshot_20230826-091620_Monero com](https://github.com/cake-tech/cake_wallet/assets/116814522/3abb72fb-a962-41db-b388-d0a1df368c6f)
![Screenshot_20230826-091826_Monero com](https://github.com/cake-tech/cake_wallet/assets/116814522/abe8b607-daea-4fa5-bfd8-2d93c066fb99)
![Screenshot_20230826-091831_Monero com](https://github.com/cake-tech/cake_wallet/assets/116814522/02a1b26d-b4ad-4e17-8a03-68b7c645e0e3)

**Comment by shortwavesurfer2009** [comment]
This is not entirely fixed. I will add checkboxes in the main post to show what is and is not fixed.

**Comment by OmarHatem28** [comment]
it's merged in `main`, but still not live in stores, we are planning to release a new version on Monday with some enhancements and fixes which will include this.

**Comment by shortwavesurfer2009** [comment]
> it's merged in `main`, but still not live in stores, we are planning to release a new version on Monday with some enhancements and fixes which will include this.

Ah, okay. I saw version 1.7.1 said it had accessibility fixes.

**Comment by shortwavesurfer2009** [comment]
This is all fixed too. Thanks for all the great work

**Comment by OmarHatem28** [comment]
anytime ^^
Thanks for your help in making the App better.
Please feel free to open other tickets for any enhancement or idea that you might think it would be good to have
