### ISSUE TITLE
Auto generate subaddress turned off result in three addresses

### ISSUE THREAD

**Issue by jan-kleks** [cake-tech/cake_wallet#1087]
I have turned on the auto generate subaddress option, and then turned it off. Now I can see in Address Book that there is a new wallet in My Wallets section, is this the newly generated sub? If it is the case, maybe it should be marked as "auto generated one"? However, with auto generate on, there are no subs listed in Address Book at all... 

If I am using the auto generate sub option would I still be able to safely use my old "main sub" address? I have it saved in one of the apps that I often use. Or do I need to change it every time?

Monero.com, iOS 15.7, iPhone 7 Plus

**Comment by SamsungGalaxyPlayer** [comment]
We can update the documentation for this to better explain what is happening.

With auto subaddresses enabled, we hide the subaddresses in the Address Book, and only show 1 option. This selects the current, next unused subaddress for that account.

If you disable auto subaddresses, then all the used subaddresses (and I believe the next unused) will appear in the address book. You can change the label names on the receive screen.

Funds sent to "old" subaddresses continue to work.
