### ISSUE TITLE
Build failures, how to compile android app in linux container?

### ISSUE THREAD

**Issue by emanuelb** [cake-tech/cake_wallet#109]
I tried to compile the android app in linux container & it fails with errors, details in: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/152#note_543405197

Also tried to recompile the latest commit https://github.com/cake-tech/cake_wallet/commit/fbf643abf419cb5d2bd75a1b5a2ffefa29d597fa with flutter 2.0.4 (instead of 1.2.6), as guessed from the commit https://github.com/cake-tech/cake_wallet/commit/ae2e55d7336f1eed1305ed147562244126658d03 that flutter > 2 is supported, which resulted in below error:

> Running "flutter pub get" in cake_wallet...                     
The current Dart SDK version is 2.10.5.
Because unorm_dart 0.2.0 requires SDK version >=2.12.0 <3.0.0 and no versions of unorm_dart match >0.2.0 <0.3.0, unorm_dart ^0.2.0 is forbidden.
So, because cake_wallet depends on unorm_dart ^0.2.0, version solving failed.
pub get failed (1; So, because cake_wallet depends on unorm_dart ^0.2.0, version solving failed.)

**Comment by tannerdsilva** [comment]
Hello,

The preliminary work to support Flutter 2 has been done, however, we have not merged that work into our `deploy` branch, which the build instructions are meant for.

Until we package that work for deployment, you should have no issues building compiling the `deploy` branch with Flutter 1.22.6 as the instructions laid out.

**Comment by emanuelb** [comment]
The Containerfile is based on the instructions in `howto-build-android.md` file (use `deploy` branch & flutter 1.22.6) & fails with errors when running `flutter build apk` (as already linked in first comment, see: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/152#note_543405197) 

> Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/appuser/app/sdk/flutter/.pub-cache/git/flutter_secure_storage-d4d68a9c1e4c45eb236cd7a5a2fac84c394a7605/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.     

> FAILURE: Build failed with an exception.
* What went wrong:                                                                                                 
Execution failed for task ':cw_monero:externalNativeBuildRelease'.                                                 
> Build command failed.                                                                                            
  Error while executing process /home/appuser/app/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/appuser/app/cake/cake_wallet/cw_monero/android/.cxx/cmake/release/armeabi-v7a --target cw_monero}
ninja: error: '../../../../../ios/External/android/armeabi-v7a/lib/monero/libwallet_api.a', needed by '/home/appuser/app/cake/cake_wallet/build/cw_monero/intermediates/cmake/release/obj/armeabi-v7a/libcw_monero.so', missing and no known rule to make it

Also running `flutter packages pub run tool/generate_localization.dart` failed with:

> Could not find tool/generate_localization.dart.
pub finished with exit code 66

which is worked when trying compile the commit (not from `deploy` branch) https://github.com/cake-tech/cake_wallet/commit/a5b10a3ac4f5676093aba1249ea13bbb3f90fc21 (which was added after my previous attempts to compile failed, read for more details the linked comments in gitlab issue: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/152#note_541461999)

Anyway will try to compile later when the next version will be published in Google-Play (just please update the docs acoordingly), I am trying to test for reproducible-builds, but currently the app in FTBFS (fail to build from source) state, and the review at: https://walletscrutiny.com/android/com.cakewallet.cake_wallet/ will probably won't be updated before the app can be at least build successfully.

building done with command `podman build --rm -t cake_build_apk_ubuntu_rolling_deploy -f ContainerfileDeploy.ubuntu` :

ContainerfileDeploy.ubuntu content: (the last steps is better to do inside the running container, as it's take lot of time for `./build_all.sh` to finish)

```dockerfile
FROM ubuntu:rolling

RUN set -ex; \
    mkdir -p /opt/android/; \
    apt-get update; \
    apt-get install --yes --no-install-recommends openjdk-8-jdk wget curl unzip automake build-essential file pkg-config git python libtool libtinfo5 cmake; \
    rm -rf /var/lib/apt/lists/*; \
    useradd -ms /bin/bash appuser; \
    chown appuser:root /opt/android/;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/app/sdk" \
    ANDROID_HOME="/home/appuser/app/sdk"

RUN set -ex; \
    mkdir -p "/home/appuser/app/sdk/licenses" "/home/appuser/app/cake/"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/app/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/app/sdk; \
    wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.6-stable.tar.xz; \
    tar xf flutter_linux_1.22.6-stable.tar.xz; \
    rm flutter_linux_1.22.6-stable.tar.xz; \
    cd /home/appuser/app/cake/; \
    git clone --branch deploy https://github.com/cake-tech/cake_wallet/; \
    cd /home/appuser/app/cake/cake_wallet/scripts/android/; \
    ./install_ndk.sh; \
    cd /home/appuser/app/cake/cake_wallet/scripts/android/; \
    ./build_all.sh; \
    ./copy_monero_deps.sh; \
    cd /home/appuser/app/cake/cake_wallet/; \
    /home/appuser/app/sdk/flutter/bin/flutter pub get; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_new_secrets.dart; \
    keytool -genkey -v -keystore $HOME/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias cake_alias -storepass cake_alias -keypass cake_alias -dname CN=IL; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_android_key_properties.dart keyAlias=cake_alias storeFile=$HOME/key.jks storePassword=cake_alias keyPassword=cake_alias; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run build_runner build --delete-conflicting-outputs; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_localization.dart; \
    /home/appuser/app/sdk/flutter/bin/flutter build apk
```

**Comment by mezzazon** [comment]
We are updating our project for flutter v.2.0.4, so we will update build instruction again soon.
As I can see issue is come because of monero lib dependencies are not available. It could happened because build_all.sh or copy_monero_deps.sh script finished wrong. I think it happened because those scripts supposes work directory as /opt/android but as I can see from provided docker file above cake wallet repository has another root directory (not /opt/android).

**Comment by emanuelb** [comment]
Used the above Containerfile with changing working directory to `/opt/android` and cloning repo into it and using tag `4.1.4` and flutter v2.0.4 and compilation works, apk file generated in `/opt/android/cake_wallet/build/app/outputs/flutter-apk/app-release.apk`.

thanks, closing this issue, here Containerfile used:

```dockerfile
FROM docker.io/ubuntu:rolling

RUN set -ex; \
    mkdir -p /opt/android/; \
    apt-get update; \
    apt-get install --yes --no-install-recommends openjdk-8-jdk wget curl unzip automake build-essential file pkg-config git python libtool libtinfo5 cmake; \
    rm -rf /var/lib/apt/lists/*; \
    useradd -ms /bin/bash appuser; \
    chown appuser:root /opt/android/;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/app/sdk" \
    ANDROID_HOME="/home/appuser/app/sdk"

RUN set -ex; \
    mkdir -p "/home/appuser/app/sdk/licenses"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/app/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/app/sdk; \
    wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.0.4-stable.tar.xz; \
    tar xf flutter_linux_2.0.4-stable.tar.xz; \
    rm flutter_linux_2.0.4-stable.tar.xz; \
    cd /opt/android/; \
    git clone https://github.com/cake-tech/cake_wallet/; \
    cd /opt/android/cake_wallet/; \
    git checkout 4.1.4; \
    cd /opt/android/cake_wallet/scripts/android/; \
    ./install_ndk.sh; \
    cd /opt/android/cake_wallet/scripts/android/; \
    ./build_all.sh; \
    ./copy_monero_deps.sh; \
    cd /opt/android/cake_wallet/; \
    /home/appuser/app/sdk/flutter/bin/flutter pub get; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_new_secrets.dart; \
    keytool -genkey -v -keystore $HOME/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias cake_alias -storepass cake_alias -keypass cake_alias -dname CN=IL; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_android_key_properties.dart keyAlias=cake_alias storeFile=$HOME/key.jks storePassword=cake_alias keyPassword=cake_alias; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run build_runner build --delete-conflicting-outputs; \
    /home/appuser/app/sdk/flutter/bin/flutter packages pub run tool/generate_localization.dart; \
    /home/appuser/app/sdk/flutter/bin/flutter build apk
```
