### ISSUE TITLE
iPhone SE 2 GUI Cuts off

### ISSUE THREAD

**Issue by FU3X** [cake-tech/cake_wallet#1142]
![image](https://github.com/cake-tech/cake_wallet/assets/97900500/b28fa37b-b13a-4bd4-8eb0-a891ff144ba4)

**Comment by tuxpizza** [comment]
Funny enough this is a problem on other phones. I've opened an internal issue. Since it's not affecting usability it's low priority for now.
Thanks for the report!

**Comment by FU3X** [comment]
> Fixed in v4.12.0

oh yeah low priority issues get fixed in 10 days? 😂

**Comment by tuxpizza** [comment]
It affected all devices, not just the iPhone SE, so it turned out to be a little higher priority and it was a easy and quick fix.

**Comment by FU3X** [comment]
> It affected all devices, not just the iPhone SE, so it turned out to be a little higher priority and it was a easy and quick fix.

Before the fix I ended up on the Iphone 15 pro max, and yes, the GUI did cut off there too
