### ISSUE TITLE
[Bug] bypass lock

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#117]
I'm able to bypass the biometric / pin lock by 

1. Opening the app and unlocking with fingerprint 
2. Put the app in the background / switch to another app. Don't remove cake from recent apps
3. Reopen cake
4. Press cancel on biometric screen to switch to pin
5. Press back button 

V 4.1.5 Google play 
Android 10

**Comment by hope-with-me** [comment]
Thank you! We'll try to fix this bug in one of the next updates
