### ISSUE TITLE
[XMR] "Bug": Transaction constructor for sending payment combines more utxos than needed

### ISSUE THREAD

**Issue by tohrxyz** [cake-tech/cake_wallet#1190]
If you want to send frequent transactions in a row, you need to have more than 1 output, because in each transaction all the input utxos are locked until it's confirmed.

Because of this, it's good to create more outputs for yourself (send fractions to different subaddresses).

BUT the problem is that when sending a transaction, wallet seems to cycle through all utxos and use more utxos than are actually needed. I found the code in https://github.com/cake-tech/cake_wallet/blob/main/cw_monero/lib/monero_wallet.dart#L205
```dart
for (final utx in unspentCoins) {
      if (utx.isSending) {
        allInputsAmount += utx.value;
        inputs.add(utx.keyImage!);
      }
    }
```

I'm not that familiar with the whole codebase, but it seems like the issue lies here.

I propose some check for the amount required and stop adding new input utxos after that is reached.
```dart
final amountToSend = <get_it_from_somewhere>;
for (final utx in unspentCoins) {
      if (utx.isSending && (allInputsAmount < amountToSend)) {
        allInputsAmount += utx.value;
        inputs.add(utx.keyImage!);
      }
    }
```

Fixing this is a crucial for the UX of this app, because if it merges your previously divided outputs into one, it fights against your effort. Thanks

**Comment by nahuhh** [comment]
Monero core prefers 2 inputs iirc.
have you compared with official wallet behavior?

**Comment by tohrxyz** [comment]
@nahuhh I've did some research and it looks like it in fact prefers to select 2 inputs (2in2out txs) for privacy.

So if anyone else from CakeWallet can confirm, we could close this, as it isn't a bug in that case.

**Comment by tuxpizza** [comment]
Yes, 2 inputs are preferred.

**Comment by tuxpizza** [comment]
BTW you can use Coin Control while sending to only choose 1 input/utxo

**Comment by tohrxyz** [comment]
@tuxpizza Any plans to integrate "PocketChange" functionality from Monerujo into Cake Wallet for Monero?

Basically opt-in setting, where wallet would try to maintain at least 6 utxos of certain size (e.g. 0.1 XMR), such that when I would want to pay several times in a row, I wouldn't be stuck at waiting for 10 confs, but would have other outputs to use?

Should I create issue?
