### ISSUE TITLE
many unlabeled buttons

### ISSUE THREAD

**Issue by shortwavesurfer2009** [cake-tech/cake_wallet#1201]
![Screenshot_20231128-060518_Monero com_1](https://github.com/cake-tech/cake_wallet/assets/116814522/12c7afe2-ce7e-4372-87d3-556f1a7cb551)
![Screenshot_20231128-060533_Monero com_1](https://github.com/cake-tech/cake_wallet/assets/116814522/c1a91827-5c48-44be-9204-0193af78aebb)
![Screenshot_20231128-060603_Monero com_1](https://github.com/cake-tech/cake_wallet/assets/116814522/22921d1d-8f17-48a4-bc10-9af9cdde24eb)

**Comment by tuxpizza** [comment]
Sorry, I don't quite understand what the issue is here. Are you expecting the on/off toggles to be labeled? They don't need to be since they are referencing the text on the left which indicates a single on/off choice.

**Comment by shortwavesurfer2009** [comment]
> Sorry, I don't quite understand what the issue is here. Are you expecting the on/off toggles to be labeled? They don't need to be since they are referencing the text on the left which indicates a single on/off choice.

Not visual labels. They would not show up on screen but talkback would read them instead of saying "button" or "unlabeled" which does not tell me their state. I would expect them to say "on" or "off" depending on their state.

**Comment by shortwavesurfer2009** [comment]
> ~Is this with talkbalk on iOS?~ I can see its Android in the screenshots nevermind :)

No, talkback is the android screen reader. The IOS one is called VoiceOver but they are very similar in function
