### ISSUE TITLE
Can't add F-Droid repo

### ISSUE THREAD

**Issue by eylenburg** [cake-tech/cake_wallet#1203]
I get the error code "Invalid repository. Contact the maintainer and let them know about the issue. org.fdroid.download.NotFoundException"

This is what I get when scanning the QR code or pasting the link with the F-Droid Basic client (https://f-droid.org/en/packages/org.fdroid.basic/)

**Comment by shortwavesurfer2009** [comment]
Same for me. For whatever reason it works in droid-ify though

**Comment by tuxpizza** [comment]
Thanks for the report, I'll take a look at this

**Comment by shortwavesurfer2009** [comment]
> Thanks for the report, I'll take a look at this. First time I've tried the QR code and yes it doesn't work right. I think F-Droid Basic is the only client that supports adding via QR code from within the app

I think the regular client does too, but only in the 1.19 alpha builds

**Comment by nahuhh** [comment]
Its not specific to qr code

**Comment by tuxpizza** [comment]
So it looks like the F-Droid basic only supports the v2 version of the F-droid index, which we currently only build for version 1.
Our build process will be updated to support v2 and the specific F-Droid Basic diff files but for now you'll have to stick with a different F-Droid client like Droid-ify or NeoStore.

**Comment by tuxpizza** [comment]
So on a second look, the stable version of F-Droid Basic (1.18.0) works just fine, but the 1.19.0 alpha version have rewritten the way the client handles repos when adding them and is currently broken with index-v1 or when not having those proper diff files. This will be closed for now as that is unstable software, please use a stable version of the client.

**Comment by nahuhh** [comment]
Should be kept open unless youre sure the next fdroid release wont break your repo

**Comment by tuxpizza** [comment]
> This will be closed for now as that is unstable software
I will reopen once 0.19 comes out in stable and if its still an issue.
It still stands that we are going to be updating our f-droid repo to index-v2 at some point regardless, to support the newer functions that the F-droid basic repo provides (Like previewing the repo before adding it)

**Comment by nahuhh** [comment]
Are you sure the issue is related to v1 vs v2?

**Comment by nahuhh** [comment]
1. Add repo to 18 = works
2. Upgrade to 19 = still works

this implies that v1 index can still be downloaded and indexed by 19, but cakes cannot be added. 

this is both fdroid and fsroid basic

**Comment by tuxpizza** [comment]
Are you saying the issue is also with the regular fdroid client? Is it the alpha version?
But upgrading from F-Droid Basic 18, adding Cake repo, then upgrading to 19 beta the repo still working?

This still indicate some sort of client issue

**Comment by nahuhh** [comment]
@shortwavesurfer2009 

should be fixed now

**Comment by tuxpizza** [comment]
Should be working now. F-Droid Basic 0.19.0 requires /fdroid/repo to be served, and we had an existing config but was slightly incorrect so it was serving the wrong path. Fixed it so it should be good now.

Thanks guys

**Comment by eylenburg** [comment]
Works now, thank you @tuxpizza

**Comment by tuxpizza** [comment]
Just updated the icon so it should show the Cake Wallet logo instead of the QR code for the repositories list
