### ISSUE TITLE
Extremely high ethereum fee?

### ISSUE THREAD

**Issue by augugusto** [cake-tech/cake_wallet#1221]
According to etherscan the current low fee is $2.61, but when I try to transfer, the fee is $6.10.
What is going on?  I have like $10 in my wallet and I want to transfer it somewhere else, but I'm not willing to overpay the fee. I've been trying to do this for like a month and it never goes low enough to be fair/at the etherscan price.

**Comment by voidastro4** [comment]
From my experience the actual fee is in line with what etherscan is telling you, Cake Wallet is just buggy with ETH.
Cake Wallet displays high ETH fees, but after sending the fees turn out to be normal.

**Comment by augugusto** [comment]
That is really unfortunate, because that means that I can't move out all of my money. It make it not trust worthy. 

I'll try it

**Comment by voidastro4** [comment]
you should be able to use the cake ETH seed to recover wallet in metamask. cake is a bad eth wallet sadly.

**Comment by augugusto** [comment]
Well. It doesn't inspire confidence to trust it with any coin.

Someone said above that it says it's that high but in reality it is not. They were right but it caused as many issues than it solved. I had $5 tried to send it all and it said $4 of fees. The fees ended up being $2. The remaining $2 were left on my account. So now I can't extract those $2 because they are not enough for the fee.

I won't trust it for anything
-------- Mensaje original --------

**Comment by nahuhh** [comment]
@OmarHatem28 @tuxpizza please take a look

**Comment by OmarHatem28** [comment]
this issue will hopefully be solved in the upcoming release, please feel free to reopen it if you still have this issue when v4.19.1 is live
