### ISSUE TITLE
Dot indicator is not visible on light theme

### ISSUE THREAD

**Issue by AndreiRegiani** [cake-tech/cake_wallet#1223]
Expected: three dots
Actual: only the current dot is visible (on several themes)

![image](https://github.com/cake-tech/cake_wallet/assets/1467605/78735536-99eb-4bff-80a1-b0aa9529f201)

Also, consider rethinking this navigation as it's not very intuitive, could be better to add labels/tabs around it so the slide is more obvious.

**Comment by fossephate** [comment]
https://github.com/cake-tech/cake_wallet/pull/1228/
