### ISSUE TITLE
"Error Installing Cake Wallet"

### ISSUE THREAD

**Issue by roweger** [cake-tech/cake_wallet#1226]
I have the repo added in F-Droid and tried updating 4.10.5 to 4.11.

When I tap to install, it attempts, but fails with a popup that says:

"Error Installing Cake Wallet"
"Failed to install due to an unknown error"

...any ideas?

**Comment by tuxpizza** [comment]
Hi, did you install Cake Wallet from a different source before?
If so, please backup all your wallet seedphrases, uninstall and then install fresh from F-Droid.

Also, what device and Android version are you using?
