### ISSUE TITLE
Cake 2FA can be bypassed - iOS

### ISSUE THREAD

**Issue by ZingyAwesome** [cake-tech/cake_wallet#1242]
Cake 2FA can be bypassed on iOS when you select any combination of require 2FA in the modify cake 2FA menu that is not a preset.

To reproduce:
-  Setup cake 2FA
- Enable any combination of "require 2FA for", but do not select a preset, for example enable only "require 2FA for all security and backup settings"
- Reopen the app and go to the show seed page, you should be asked for 2FA
- Back out to the wallet balance display page
- Go back to the show seed page, you will no longer be asked for 2FA and your seeds will be shown
- (If 2FA is still prompted you need to exit and reopen the app and repeat the last 2 steps)

After performing the above process, 2FA gets disabled. If you go to the modify 2FA page you will see that all the sliders have been set to false. 
This doesn't seem to happen if you select a 2FA preset. I am unsure whether this affects other platforms other than iOS.

**Comment by tuxpizza** [comment]
This will be fixed very soon. Thanks for the report! 🫡
