### ISSUE TITLE
Advenced coin control

### ISSUE THREAD

**Issue by izhastron** [cake-tech/cake_wallet#1244]
Hello, I would like to suggest an improvement. In the “recieve” section, add a button to change address or the ability to create a pool of addresses. I want to use an application to generate 20 addresses, which will then be used in another application and which will decide whether coins have arrived or not, based on blockchain blocks (without private keys), i.e. without transferring control of coins to a third-party application based on full node.

**Comment by nahuhh** [comment]
You can do this with subaccounts and subaddresses for each account

Turn off "auto generate subaddresses" under "settings > privacy"

**Comment by tuxpizza** [comment]
What @nahuhh said. If you turn off auto generate sub addresses, you can freely view, name, and create subaddresses, and also can create separate "accounts" for seperated balance and address pools.
