### ISSUE TITLE
Missing a transaction

### ISSUE THREAD

**Issue by normanu** [cake-tech/cake_wallet#1246]
I have added my wallet with seed phrase after syncing is complete I miss one transaction, so the balance is incorrect.
I checked both with Feather and Monerujo, those balances are correct.
Did  resyncing 5 times, but it always misses the same transaction. (from 28-06-2023)

What could be wrong?

**Comment by normanu** [comment]
Changed the end point from xmr-node.cakewallet.com to nodes.hashvault.pro and now it is fixed.
Seems there is a issue with Cakewallets own node.

**Comment by tuxpizza** [comment]
Have you had any issues with the Cake Wallet Monero node since then?

**Comment by normanu** [comment]
To be honest as it was missing a transaction and after trying several times to resync and it not showing up, I went back to Monerujo

**Comment by normanu** [comment]
Yes it was a transaction inbetween which was missing.
Not the first.

**Comment by tuxpizza** [comment]
This is indeed a weird issue, sorry it has caused you problems. 
Can I ask what Cake Wallet version you were using and what phone/OS version?

**Comment by tuxpizza** [comment]
I would also suggest trying to delete that wallet and restoring it from scratch once more.

**Comment by normanu** [comment]
It was the latest from the playstore at the time from opening this ticket
on a OnePlus Open (Android).

Op wo 17 jan. 2024 19:34 schreef tuxsudo ***@***.***>:

**Comment by tuxpizza** [comment]
Unfortunately we have not received any other reports of this issue with our Cake Wallet Monero node, so for now I will close this issue since there isn't anything for us to look into as everything appears to be working fine. I would suggest deleting / reinstalling Cake Wallet and seeing if you can import that wallet again and have that missing transaction show up. Thanks!

**Comment by normanu** [comment]
I did that three times unfortunately.
Ill try again at a later moment

Op vr 19 jan. 2024 17:28 schreef tuxsudo ***@***.***>:
