### ISSUE TITLE
Monero Sync Progress Resets to Zero

### ISSUE THREAD

**Issue by cahlenlee** [cake-tech/cake_wallet#1253]
After achieving a complete XMR Sync and maintaining it for several days, Cake Wallet always eventually resets itself to 0 and starts all over.

This causes me to be unable to use my Monero for days each time because the sync progress is consistently lost when the app goes into the background.  I also get crashes occasionally while syncing.

These three problems in combination make the XMR experience on Cake EXTREMELY FRUSTRATING! 🤬

It's been like this for months, and it was so obvious and consistent that I figured someone would be working on it, but it's still the case in 4.12.1, Android 13, Pixel 4 XL.  It also occurs on my LG V20 running Android 12.

**Comment by nahuhh** [comment]
#1213
