### ISSUE TITLE
why is cake pay market place not in the app anymore?

### ISSUE THREAD

**Issue by FU3X** [cake-tech/cake_wallet#1258]
for me when i click the button it launches in the web browser

**Comment by tuxpizza** [comment]
If you're talking about the Cake Pay Web Cards its because Cake Pay only works in the browser, we have yet to re-implement Cake Pay into the app.

**Comment by FU3X** [comment]
> If you're talking about the Cake Pay Web Cards its because Cake Pay only works in the browser, we have yet to re-implement Cake Pay into the app.

is this a high priority?
