### ISSUE TITLE
GNU/Linux build instructions

### ISSUE THREAD

**Issue by Spixmaster** [cake-tech/cake_wallet#1270]
I want to package this software for the Arch user repository but am unable to do so. Please provide the build instructions for GNU/Linux.

**Comment by tuxpizza** [comment]
Because Cake Wallet for Linux is still in beta, its not currently in main. Please use the Linux build guide https://github.com/cake-tech/cake_wallet/blob/cw_linux_direct_input_password/build-guide-linux.md under the https://github.com/cake-tech/cake_wallet/tree/cw_linux_direct_input_password branch

**Comment by Spixmaster** [comment]
Thanks!
