### ISSUE TITLE
I can not enter.  Russian language removed

### ISSUE THREAD

**Issue by jmatg1** [cake-tech/cake_wallet#1289]
I decided to check if I could log into my wallet.  I saved the phrase and made a backup.  Logged out of my account.  I went through the phrase, but didn’t find my money.  There is no backup.  Updated the application.  There is a backup, but it doesn't work.  Now I can’t even log in, because the Russian mnemonic phrase has been removed

**Platform:**
 - OS: Android 14
 - Cake Wallet Version: last

**Comment by tuxpizza** [comment]
Hi, Russian language has not be removed or changed, these are the valid words for a Russian mnemonic
https://github.com/cake-tech/cake_wallet/blob/main/cw_monero/lib/mnemonics/russian.dart
