### ISSUE TITLE
Monero: Subaccount missing after 25 words recovery

### ISSUE THREAD

**Issue by derjohn** [cake-tech/cake_wallet#1302]
**Describe the bug**
I did a wallet recovery with 25 words and it basically works. The main Wallet has 0 XMR. It has a subaccount (not a subaddress) with some XMR. But the subaccount does not show up on the recovered device. I synced the chain from a date before wallet creation.

**To Reproduce**
Here are my 25 words .... eh ..... better not ;)

**Expected behavior**
The subaccount should appear automatically.

**Platform:**
 - OS: Android / GrapheneOS
 - Device: Pixel7
 - Cake Wallet Version: latest from playstore. I can't find a version info within the app.

**Additional context**
I am not bankrupt and I could workaround by transferring the XMR (I still have my old device). I just wanted to report the issue. Maybe the cause is that the primary wallet is 0 XMR and never had any transaction?

**Comment by tuxpizza** [comment]
Hi, please re-create that sub account with the exact same name and the funds will show up
