### ISSUE TITLE
Biometrics won't activate in settings (Oreo 8.1.0)

### ISSUE THREAD

**Issue by ins2d** [cake-tech/cake_wallet#133]
Can't activate biometric unlock on my OnePlus 6 @ 8.1.0 Oreo.

APK 4.2.0 form github, same as any other version

1) Open Settings
2) Tap 'Use biometric'
3) Enter Pin
4) Goes back to (1) with biometrics still off

Would be nice if you look into this :)
P.S. Every other wallet works with that just fine!

Tnx! :-*

**Comment by hope-with-me** [comment]
Thank you for your request. We will look into this issue

**Comment by hope-with-me** [comment]
Hi. Could you check this issue on 4.2.3?

**Comment by ins2d** [comment]
Fails on flutter/firebase call. Must not depend/rely on those IMO. How do you plan supporting F-Droid version with these? :)
Thanks for looking into it. Let's make it perfect (without redundant SDKs dependencies) shall we? :))))


![image](https://user-images.githubusercontent.com/20364046/121817019-8c370780-cc87-11eb-9c24-5d5872dd4f1f.png)

/

**Comment by SamsungGalaxyPlayer** [comment]
Does this issue persist?

**Comment by ins2d** [comment]
> Does this issue persist?

Yep, same result on 4.3.6, except it just crashes on step #4 from the OP.

Some clues from the log:

---
zygote64 [info]
... ClassNotFound ... android.view.View$OnUnhandledKeyListener ...
---
FingerprintService [error]
handleError (client = ...cake... , error = 5 )
---

Also these:

https://i.postimg.cc/VvCMT9Td/photo-2022-02-03-18-37-58.jpg


P.S. I'm note a dev, plus my device is pretty "custom" and partially de-googled. Other apps (well, 99% let's say) work with fingerprint just fine, FOSS/PlayStore - any kind/source. I'd really want to help with that as I feel it's more of an app issue, not the device itself (custom setup doesn't make it easy though, I understand that!).


Thank you for your commitment and great products!

**Comment by nahuhh** [comment]
@ins2d 

Still?

**Comment by ins2d** [comment]
> @ins2d
> 
> Still?

Will have to check later when I'm back on a proper connection (data plan) and able to update. Will keep you posted! 🙏❤️

**Comment by stefantaubert** [comment]
I have a similar problem but in my case the app closes and the Android homescreen is displayed (app still open in the background). It is not possible to activate biometrical authentication. I am using version `monero.com_1.0.6.apk`.

**Comment by ins2d** [comment]
> @ins2d
> 
> Still?

Tested on both Cake and Monero - still kind of the same.

Cake v4.4.1 was uninstalled and installed fresh, new wallet created
Monero v1.0.6 - 1st and fresh install, new wallet.

Logs from both (run > go to setting > try to activate bio > confirm pin > crash 'app has stopped'):

[Cake_log_2022-06-05-18_10_49.txt](https://github.com/cake-tech/cake_wallet/files/8840225/Cake_log_2022-06-05-18_10_49.txt)
[Monero_log_2022-06-05-18_16_01.txt](https://github.com/cake-tech/cake_wallet/files/8840226/Monero_log_2022-06-05-18_16_01.txt)

Hope this helps! ❤️

**Comment by SamsungGalaxyPlayer** [comment]
Please test with 4.4.8 when released, or the beta build

**Comment by SamsungGalaxyPlayer** [comment]
@ins2d @stefantaubert 

Can you please check with Cake Wallet 4.5.0 and/or Monero.com 1.2.0?

**Comment by stefantaubert** [comment]
Tested it again with Monero.com 1.2.0_28 and it still doesn't work.

**Comment by tnonate** [comment]
This issue still persists. It was in the latest version of Android 13 as of the August 5 security update (Build TQ3A.230805.001.A2) and also in Calyx OS 4.11.3 (build TQ3A.230705.001.23411030). It will activate the "unlock with biometrics" option, however it will still prompt you for a PIN regardless.

If this is a different issue, I apologize and let me know so I can open a separate ticket.

**Comment by tuxpizza** [comment]
Is this still an issue for any of you?

**Comment by tnonate** [comment]
So sorry, I totally forgot about this comment.

On my end, it was user error. I'm using Cake Wallet in a work profile, and it turns out that when you make a work profile you need to set up biometrics all over again for that profile. Once I did that, it's working as expected.

**Comment by tuxpizza** [comment]
> So sorry, I totally forgot about this comment.
> 
> On my end, it was user error. I'm using Cake Wallet in a work profile, and it turns out that when you make a work profile you need to set up biometrics all over again for that profile. Once I did that, it's working as expected.

Great! I'll close this issue for now
