### ISSUE TITLE
In desperate need of "pull to refresh" functionality

### ISSUE THREAD

**Issue by tohrxyz** [cake-tech/cake_wallet#1352]
it happens so often that i come back into the app and the current data is not the freshest and i need to wait for auto refetch or go painstakingly into settings and hit reconnect.

really easy improvement would be to allow userd to pull from the top using slide gesture and this would trigger manual refresh

i desperately need this to come to the app.

or add refresh button to homescreen. something like this, please

**Comment by tuxpizza** [comment]
I've definitely noticed myself, sometimes if I manually "Reconnect" it makes transactions showup on the transactions page a little sooner. (even if it already says "Synchronized"). Will try out this idea

**Comment by tohrxyz** [comment]
yeah, i mean app being smart enough to auto-fetch when it's needed is a good thing for ux, but when there's an edge case or it can't decide to re-fetch in some scenario, it's better to have a manual option to do so.

i would propose 'pull-to-refresh- being in the home screen and also in the transaction history list screen.

having it in both just makes sense.

**Comment by tohrxyz** [comment]
i saw that this was already merged to main in https://github.com/cake-tech/cake_wallet/commit/a0820e8a7358fb25d304979fba1d9cfe0519925a , so i think it makes sense to close this as completed, gj CW team!
