### ISSUE TITLE
Entire Balance Missing (BTC)

### ISSUE THREAD

**Issue by kn0wmad** [cake-tech/cake_wallet#136]
A new wallet with 1 incoming tx, which cleared several days ago, and previously showed a balance, now shows a zero balance. There are 0 outgoing txs, and attempting to create a tx results in the error: No inputs for the tx.

Have tried the following:
Verified utxo on blockchain (thousands of confirmations), reboots, reconnects, changing nodes

Maybe there's a caching issue of some kind?

**Comment by alphaonion** [comment]
I have the EXACT same problem.  I have sent the required messages to case@cakewallet.com and got returned mail.  I just tried again from a third email account hopefully it works because I haven't heard anything regarding my case.

**Comment by hope-with-me** [comment]
Unfortunately, we don't have an access to the investigation. Please contact again to case@cakewallet.com

**Comment by alphaonion** [comment]
I have many many many many times from different email providers.  Its obvious you are trying to EVADE even acknowledging receipt of my emails.  
A simple "We got your email but we cant do anything about it" would be a start.  I have requested monero DELIST your wallet on their recommended wallet page and Im spreading the word what you guys have built an INSECURE wallet.

**Comment by hope-with-me** [comment]
Please provide me your case number, I'll forward it to the team

**Comment by alphaonion** [comment]
> Please provide me your case number, I'll forward it to the team

Just sent it. Thank you

**Comment by hope-with-me** [comment]
Sorry, I don't see it. What's your email?

**Comment by alphaonion** [comment]
<e258868f-433b-403d-8a74-c942ed433afd>

**Comment by alphaonion** [comment]
Just wanted to say, cake wallet NEVER helped me or even responded to any email I sent them.  Does anyone see this?? Beware
