### ISSUE TITLE
Issues with Syncing on Monero.com Wallet

### ISSUE THREAD

**Issue by TempUser13** [cake-tech/cake_wallet#1360]
When I open the app, it will start syncing from the start or it will go so far then the app closes and it'll potentially go back to the start or resume from where it was.

**To Reproduce**
Use the app like normal

**Expected behavior**
I don't have to resync the entire blockchain every time I open the app.

**Screenshots**

Pixel 8 Pro, GrapheneOS 2024040200, Monero.com 1.12.0

**Comment by tuxpizza** [comment]
Hey, unfortunately this was caused by Background sync instability and we've removed background sync in the latest version until we can re-implement in a better way. Please update to 1.12.1 and the problem should go away.

**Comment by TempUser13** [comment]
Thank you for the reply, I've updated to 1.12.1. Could there be an in app new version notice and is there any update on the split architectures apks? Thanks again.
