### ISSUE TITLE
monero.com, changenow.io refused to connect

### ISSUE THREAD

**Issue by Weltolk** [cake-tech/cake_wallet#1366]
**Describe the bug**

**To Reproduce**
1. open https://monero.com/

**Expected behavior**
A clear and con`cise description of what you expected to happen.

**Screenshots**
![image](https://github.com/cake-tech/cake_wallet/assets/40228052/b30dff3d-66c9-4061-b875-90d5b824a519)

**Platform:**
 - OS: [e.g. iOS 15.1, Android 14]
 - Device: [e.g. iPhone 14, Galaxy S21]
 - Cake Wallet Version: [e.g. 4.12.1]

**Additional context**

**Comment by tuxpizza** [comment]
Looks like it may be an issue on your end, something is either blocking changenow.io via DNS or you have a strict browser setting preventing it from loading an external widget

**Comment by Weltolk** [comment]
> Looks like it may be an issue on your end, something is either blocking changenow.io via DNS or you have a strict browser setting preventing it from loading an external widget

I tried other browsers (firefox, chrome), the problem persists

I tried to access changenow.io directly, and it works fine

I tried using a proxy to change the ip address and change the dns resolution address, the problem persists

Grabbed a packet through edge's developer tools and found a request to access the changenow.io widget, copying the url to edge and accessing it directly will display the widget correctly.

When I use firefox to access, firefox gives more detailed error report, think it is the setting of the website of changenow.io that cause the problem:
```
Firefox Can’t Open This Page

To protect your security, changenow.io will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

[Learn more…](https://support.mozilla.org/1/firefox/124.0.1/WINNT/en-US/xframe-neterror-page)
```

Learn more: https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct
