### ISSUE TITLE
Rotate subaddresses per exchange

### ISSUE THREAD

**Issue by sethsimmons** [cake-tech/cake_wallet#139]
Hi there,

I had a Cake Wallet user reach out to me with a privacy concern as they noticed that Cake Wallet does not rotate addresses with each use of the exchange feature, and instead relies on the primary address for all exchanges to Monero.

While this doesn't leak any privacy past the point of exchange, it makes it trivial for the exchange being used to link trades back to the same entity which can be quite detrimental to privacy, especially when trading from Bitcoin or another transparent chain.

Utilizing a new subaddress per trade should be done automatically, behind the scenes, and never re-use subaddresses to ensure that it is not trivial for the exchange to link trades to a single entity (at least on the Monero end of the trade).

**Comment by nahuhh** [comment]
Do other monero wallets auto rotate addresses? 
@sethsimmons 

Personally, I have a specific subaddress setup for each exchange website I use, on a subaccount.

Agreed that I do not like / agree that the default swap address is the main accounts 1st address. 
I would like to set that to a specific subaddress.

**Comment by sethsimmons** [comment]
> Do other monero wallets auto rotate addresses?
> @sethsimmons
> 
> Personally, I have a specific subaddress setup for each exchange website I use, on a subaccount.
> 
> Agreed that I do not like / agree that the default swap address is the main accounts 1st address.
> I would like to set that to a specific subaddress.

https://featherwallet.org/ rotates subaddresses for each receipt of funds, and I'm hopeful other wallets will follow suit. The minimum recommendation is rotating sub-addresses per entity you interact with, but when interacting anonymously with an exchange, ideally you would rotate each time so they cannot trivially link your exchange trades back to the same entity.

The minimum requirement I would say here is a subaddress per exchange service, but as mentioned ideally it would be per trade.

**Comment by nahuhh** [comment]
Meanwhile, trust wallet stopped rotating even btc addresses. ... questionable. 

.. Agreed. The built in exchange service should auto use each subaddress only once. 

Perhaps when creating a subaddress, the option to have it "rotate after each use" is in order.

I don't want all of my address being rotated by default. Each person I deal regularly with has their own subaddress. 

I would, however, like to set an "exchange" or "single use" subaddress, and this address would rotate everytime.

**Comment by sethsimmons** [comment]
I agree that the general use of subaddresses does not need to rotate automatically, I like (for example) in Monerujo how you can create at will and label clearly each subaddress.

But yes, exchanges should auto-rotate per trade, and anytime you're not sure you should use a new subaddress.

**Comment by sethsimmons** [comment]
Resolved via 4.2.4:

https://twitter.com/cakewallet/status/1420015941002436612?s=20
