### ISSUE TITLE
Ui scrollbar on swap choice overlap and unnecessary 

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#140]
https://user-images.githubusercontent.com/50635951/119731622-294f0f00-be45-11eb-97c6-dcbdf73a997b.mp4

**Comment by hope-with-me** [comment]
Could you provide us more details about your device?

**Comment by nahuhh** [comment]
![Screenshot_20210531_055446.jpg](https://user-images.githubusercontent.com/50635951/120175940-b7741e00-c1d4-11eb-8ece-7a96cf77d77a.jpg)

**Comment by hope-with-me** [comment]
Hi. Could you check this issue on 4.2.3?

**Comment by nahuhh** [comment]
> Hi. Could you check this issue on 4.2.3?   

![Screenshot_20210611_121841.jpg](https://user-images.githubusercontent.com/50635951/121717452-2db73100-caaf-11eb-82a5-ae0e6dace20e.jpg)

The overlap for usdterc20 is fixed due to moving it to a new location 

But the scrollbar is still located "inside" the squares

Question and suggestion 

Q. What is "usdt" ? I assumed that was the erc20. Is it the trc20?

S. Instead of "usdterc20", display multiple lines, like:
 USDT 
ERC20 

(If "usdt" is the trc20, I suggest the same for that. Multiline display)
