### ISSUE TITLE
DFX Connect fails

### ISSUE THREAD

**Issue by dis-grace** [cake-tech/cake_wallet#1405]
**DFX conncet fails on linux**
When trying ot buy from DFX connect the desktop app yields an error which says

`Provider unavailable: Invalid argiment(s): Failed to lookup symbol 'sign_message': /opt/cake-wallet-bin/lib/libflutter_linux_gtk.so: undefined symbol: sign_message`

Installed both from AUR and Flatpak, same issue

**To Reproduce**
1. Click on 'Buy'
3. Click on 'DFX Connect'

**Screnshot**
![immagine](https://github.com/cake-tech/cake_wallet/assets/148250794/3444664e-e95e-4d62-884a-20aa82b976e1)

**Platform:**
 - OS: Endeavouos (Arch derivative)
 - Cake Wallet Version: 4.15.4

**Comment by tuxpizza** [comment]
Will check with the team on this, thanks for the report

**Comment by TaprootFreak** [comment]
Hi folks

I would say this problem is fixed and the issue can be closed.
