### ISSUE TITLE
Send page improvements 

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#141]
1. Currently when selecting send "all", no value is shown. If this is not shown due to the fee having to be included, I would at least have it show an approximate value 

2. Available balance on send screen should also show in fiat denomination directly below the crypto quantity. 
2a.  add "XMR/LTC/BTC" to the end of the quantity. (Currently all #s)

3. The estimated fees (on xmr. Untested on ltc or btc) don't match the fees after pressing send. 
0.00012305 fee turns into 0.00000978. 
Thats over 12x difference. 

4. If you send the app to the background and it disconnects, upon returns you are not given any indication of being disconnected. 
You are able to finish entering transaction details, but when you try to send you are given an error: "wallet is not synced"

You then have to abandon the transaction, return to home screen and "reconnect"

My suggestion would be:
When returning, if the app is "disconnected" the "send" button should appear as "reconnect and send". 

5. When selecting a saved address or template, the "name" should be shown above the address.

6. Templates should be listed vertically. Or in a drop down list. Or submeny.
 Even 2 is too much scrolling.
6a. The ability to sort the list (manually, AZ, amount $, quantity)

7. When creating a template, it allows you to _enter_ a dollar amount but only remembers the quantity of crypto. 
If I enter 50$ on a template, the template should be "50$”. 

I understand that some will want to calculate the amount of crypto.

Perhaps a selection box on the template creation page as to whether the template uses the fiat value or the crypto quantity

**Comment by SamsungGalaxyPlayer** [comment]
I am going to close this issue because it includes many different things all in 1, but they are good recommendations. I have made notes to improve the following:

* Display approximate fiat value if ALL is selected
* More accurate estimated fee calculation for XMR
* Adding a small connection indicator on the Send and Exchange screens
* Template expander in case of >2
