### ISSUE TITLE
Unable to add notes to TXs

### ISSUE THREAD

**Issue by mikson022** [cake-tech/cake_wallet#1421]
Attempt to add a note on TX yields no result as if the note wasn't added. Successfully adding a note is ONLY available at the construction of payment but even then it doesn't properly display at Transactions tab, it's only visible at Transaction Details tab.

1. Go to Transactions tab
2. Click on a TX (Transaction Details tab)
3. Scroll down to 'Note (tap to change)'
4. Input the note and leave the Transaction Details tab
5. Go back to Transactions tab, your TX doesn't have a note

Platforms (3):
 - OS: Android 11, Device: Redmi Note 8 Pro, Cake Wallet 4.14.4 and 4.14.5
 - OS: Android 12, Device: Redmi Note 9 Pro, Cake Wallet 4.14.5
 - OS: Android 13, Device: Motorolla G84, Cake Wallet 4.19.5

**Comment by mikson022** [comment]
Are there any updates regarding this issue or will it be addressed later due to more important fixes and features?

**Comment by OmarHatem28** [comment]
This should be solved in the latest version 4.20.0
Thanks for opening the issue

please reply here if the issue is not fixed and we can re-open it
