### ISSUE TITLE
Unable to show Wallet seed

### ISSUE THREAD

**Issue by dumbasPL** [cake-tech/cake_wallet#1459]
**Describe the bug**
The `Wallet seed` section in `Wallet seed/keys` is empty. Unable to see the seed phrase.

**To Reproduce**
1. Go to `Burger menu` -> `Security and backup` -> `Show seed/keys` -> `Enter your PIN` -> `Wallet seed/keys`
2. See that all the public and private keys are present
3. See that the space for `Wallet seed` is empty
4. Click on the empty space where the seed should be
5. Android confirms that something has been copied to the clipboard
6. Check the contents of the clipboard and see that they are also empty

**Expected behavior**
I can see and/or copy the mnemonic seed phrase

**Screenshots**
nope, not posting that. But It's pretty easy to imagine, the space for it is just blank.

**Platform:**
 - OS: Android 14 (Stock ROM)
 - Device: Google Pixel 7 pro
 - Cake Wallet Version: 4.16.2

**Additional context**
I am unsure how the wallet was created (new or restored) but I believe it was restored

EDIT: Also tried the QR code and got `monero-wallet:?seed&height=0000000` (height redacted, but it was correct)

**Comment by ywiyogo** [comment]
This bug happens in the Monero wallet. BTC wallet shows the seed phrase.

**Comment by authorisation** [comment]
I am also experiencing this on iOS, is there any other way to read the seed?

**Comment by OmarHatem28** [comment]
are the public and private keys correct? or are they just 0s like the image below
if they have the correct value, can you try restoring the same wallet with the private key, and see if it will get the seeds correctly or it would still be empty?

also can you remember when this wallet was created? and whether it was created with a polyseed or legacy seed

![image](https://github.com/user-attachments/assets/6db64cfa-24b3-48d4-b454-f999e5a35668)

**Comment by dumbasPL** [comment]
> are the public and private keys correct? or are they just 0s like the image below if they have the correct value

The keys were correct, only the seed phrase was missing.

> can you try restoring the same wallet with the private key, and see if it will get the seeds correctly or it would still be empty

I transferred all the funds to a new wallet and deleted the app

> also can you remember when this wallet was created? and whether it was created with a polyseed or legacy seed

Already stated in the original post that I don't remember if it was even restored. Now that I think about it, judging by the fact that I didn't have a backup of it (literally the reason why I wanted to see the seed phrase in the first place) I'm guessing it wasn't restored and just created in the app.

Also just tested the app (fresh install) and when I create a wallet using polyseed I see both seeds on the wallet seed/keys page but when I create another wallet using legacy I only see their legacy seed. I remember only seeing one seed field so it must have been a legacy seed (unless that changed in between my initial report and now)

Also not sure if this matters, but I also faintly remember making a new wallet (in the app) and deleting the original one at some point, not sure if that was the same install though. Tested this now and seems to work fine so idk if related.

**Comment by dumbasPL** [comment]
ok, managed to break it

steps to reproduce:
1. create a wallet in the official monero app
2. go to to `Settings` -> `Show seed & keys`
3. scroll down until you see the QR code and make sure `Spendable Wallet` is selected
4. install a fresh copy of cake wallet and attempt to restore it from a QR code
5. go to `Wallet seed/keys` and notice that the seed is missing

version: 4.19.1 (play store)

> can you try restoring the same wallet with the private key, and see if it will get the seeds correctly or it would still be empty

Just did, and this also causes the seed to be empty. Is there no way to calculate the seed from the keys, is that what's happening here? If so it should be more clear in the UI why the seed is missing IMO

steps to reproduce the same as above but using keys instead of qr.

**Comment by OmarHatem28** [comment]
yup thanks for providing these details, we found where the issue of empty seeds and wrong keys is coming from

and in your case, yup you can't derive the seeds from the keys, so if you restore from keys, then the seeds would be empty indeed, and I believe the qr made by monero desktop app shows the keys, thus Cake restores from the keys.

we improved the UI to hide the wallet seeds for wallets that were restored via keys

Appreciate your feedback and your effort to reproduce it with us, thank you
