### ISSUE TITLE
Exchange transaction status not reflective of underlying changenow status

### ISSUE THREAD

**Issue by Recodify** [cake-tech/cake_wallet#1472]
**Is your feature request related to a problem? Please describe.**
When performing an exchange from one currency to another, the transaction initially shows as "pending". As soon as it's confirmed, it is updated to "sent".  However, this is not really accurate. If you take the tradeId and view this transaction using the URL https://changenow.io/exchange/txs/[tradeId], you see that the exchange is still currently in progress.

**Describe the solution you'd like**
A deep link to the txs on changenow is the simplest solution. A even nicer solution would be to integrate the changenow exchange process statuses to cake so that these are propagated back to the transaction history.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/cake-tech/cake_wallet/assets/5644228/a0a56079-4104-494f-84a3-89f2cc9d733a)
![image](https://github.com/cake-tech/cake_wallet/assets/5644228/f84bd72c-4761-40fe-bb6d-a655596f46bb)

**Comment by tuxpizza** [comment]
I think you're reading the "Sent" transaction incorrectly. It's not talkiong about whether Changenow has sent the swapped funds to you or not, it's about having sent a Litecoin transaction (which in this case, just happens to be to ChangeNow).

If you tap on the ChangeNow swap transaction (the middle one) you will see the status of the swap.
