### ISSUE TITLE
Bug switching wallets

### ISSUE THREAD

**Issue by CodeCracker-oss** [cake-tech/cake_wallet#1484]
**Describe the bug**
When switching from litecoin wallet to Monero wallet, it gives messages of "loading <wallets name> wallet" and just freezes apps, which unfreezes when clicking back or swiping message away. Never actually loading the monero wallet. I am unsure if this happens woth other wallets or not.

**To Reproduce**
1. Go to 'menu icon'
2. Click on 'wallets'
3. Click on wallets name
4. See the loading message thats loads continuously.

**Platform:**
 - OS: Android 14
 - Device: Pixel 8
 - Cake Wallet Version: 4.18.1

**Additional context**
Same issue occurs on prior version of Cake Wallet 4.18.0, have not tested any other version. Uninstall/Reinstall does not address issue.

**Comment by BitcoinQnA** [comment]
I am also experiencing the same thing on a Pixel 6a running 4.18

**Comment by tuxpizza** [comment]
Does this apply to a new Monero wallet you create or is it just ones from previous versions?

**Comment by BitcoinQnA** [comment]
@tuxpizza I'm a first time Cake user with a new Bitcoin and Monero wallet.

**Comment by BitcoinQnA** [comment]
Here is what happens with mine. I cut the video short, but it just hangs on the loading screen.


https://github.com/cake-tech/cake_wallet/assets/64638670/6d27504a-a3ac-4537-bd95-6b62d70428e5

**Comment by BitcoinQnA** [comment]
@CodeCracker-oss is there any more info I can get you to assist in troubleshooting here?

**Comment by tuxpizza** [comment]
@BitcoinQnA did you try reinstalling and re-importing your seed

**Comment by BitcoinQnA** [comment]
@CodeCracker-oss my apologies, I tagged the wrong person in my previous post.

@tuxpizza this seemed to do the trick. Side question, what's the reason for you guys using the Electrum seed format instead of BIP39 like the rest of the industry?

**Comment by tuxpizza** [comment]
> @CodeCracker-oss my apologies, I tagged the wrong person in my previous post.
> 
> @tuxpizza this seemed to do the trick. Side question, what's the reason for you guys using the Electrum seed format instead of BIP39 like the rest of the industry?

I'm not 100% sure why this is the way for BTC/LTC, this was a decision made by somebody years ago to use Electrum. We're actually in the process of switching to BIP-39 by default for our Bitcoin and Litecoin wallets to allow users to more easily use 1 seed for many wallets. We recently added BIP-39 restore support to those wallets, and the rest of our wallet types (Excluding monero) already use BIP-39 by default when creating a new wallet.

**Comment by tuxpizza** [comment]
Glad the reinstall fixed that for you, it must have just been some weird wallet corruption which happens in rare cases. I'll be closing this issue for now as it appears to be resolved for both of you :wink:
