### ISSUE TITLE
Unable to clone repo under OSX

### ISSUE THREAD

**Issue by hbs** [cake-tech/cake_wallet#1494]
**Describe the bug**

A git clone no longer works in my OSX setup, the issue seems to be that some files have an emoji in their name and git complains with the following error:

error: unable to create file .github/ISSUE_TEMPLATE/bug-report-🪲-.md: Illegal byte sequence

**To Reproduce**

git clone git@github.com:cake-tech/cake_wallet.git

**Expected behavior**

git clone should work.

**Screenshots**

N/A

**Platform:**

OSX

**Additional context**

**Comment by tuxpizza** [comment]
This is a weird problem that I haven't seen, I guess I could try removing the emojis from the issue templates. What version of macOS? I hope it's not actually OSX haha

**Comment by hbs** [comment]
The issue is because of the emoji present in this file name:

.github/ISSUE_TEMPLATE/feature-or-enhancement-request-✨.md

The machine it fails on is running an old OSX 10.15

**Comment by tuxpizza** [comment]
Let me know if you are able to clone the repo now

**Comment by hbs** [comment]
Works like a charm now, thanks! Will be able to push more PR ;-)
