### ISSUE TITLE
Please removing these unnecessary permissions

### ISSUE THREAD

**Issue by serrq** [cake-tech/cake_wallet#1501]
Cake 4.18.2

Unnecessary and unsafe in my opinion.
We have to reduce the attack surface.

Unless they have an utility that I missed.

![1000113855](https://github.com/cake-tech/cake_wallet/assets/113377431/cc8c7a4e-45b2-4114-b6a2-57903a923aa3)

**Comment by tuxpizza** [comment]
These are part of the "Nearby Devices" permission which is required to use Bluetooth with hardware wallets. If you have not granted Cake Wallet the "Nearby Devices" permission, then it won't have the capabilities in the image you sent above.

**Comment by tuxpizza** [comment]
Yes, it's part of the "Nearby Devices" permission.
