### ISSUE TITLE
Can ETH wallets be supported in the future?thank you 

### ISSUE THREAD

**Issue by xt1085** [cake-tech/cake_wallet#153]
Can ETH wallets be supported in the future?thank you

**Comment by SamsungGalaxyPlayer** [comment]
This is planned.

**Comment by APN-Pucky** [comment]
Is the branch https://github.com/cake-tech/cake_wallet/tree/CW-78-Ethereum stable enough to test it?

**Comment by SamsungGalaxyPlayer** [comment]
@APN-Pucky definitely NOT stable yet (nor security reviewed yet), but you are welcome to give it a try if you're a developer!
