### ISSUE TITLE
[Feature Request] - connect to receivers remote node for instantaneous tx

### ISSUE THREAD

**Issue by Gingeropolous** [cake-tech/cake_wallet#154]
an idea for mobile wallets to increase the speed of tx. In the QR code, include information about the receivers connected node (IP address). That way the sender can connect directly to the receivers node, and the transaction will be instantaneous. 

i've noticed with mobile wallets since the introduction of dandelion that sending something, say, between 2 cakewallets standing right next to each other can take minutes ... or even just 1 minute, which feels slow in the modern age, because the tx bounces around the network until it fluffs. This bouncing is great, but for the 2 people standing right next to each other, its silly. 

there is at least 1 edge case to consider that could mess the whole thing up, where the receiver is on 1 network (say a home network connected to a home node), and the sender is connected to another network (like, through their mobile data). The sender wouldn't be able to resolve the internal networks IP, so there'd need to be some kind of fallback timeout thing

re: losing dandelion benefits, I don't think it will. it will still stem out from the receivers node.

perhaps this could become a standardized format for mobile monero QR codes to be used by any mobile wallet.

**Comment by selsta** [comment]
It's easier to use a node that is setup over Tor with --tx-proxy tor,127.0.0.1:9050,disable_noise

Then you still get privacy benefits from Tor without having to wait for Dandelion.

Try using 88.198.199.23:18081 as your remote node and your transactions should show up instantly at the receiver side.

**Comment by Gingeropolous** [comment]
> Try using 88.198.199.23:18081 as your remote node and your transactions should show up instantly at the receiver side.

you mean if both wallets are connected to that node?

**Comment by selsta** [comment]
No. The other wallet doesn't matter.

**Comment by SamsungGalaxyPlayer** [comment]
This is likely undesired, since it could easily lead to users unintentionally sharing their IP addresses with the recipients, or more easily open up the door to malicious nodes. I am going to close this issue since we don't want to go out of spec for this. If this Monero community comes up with a clever way to handle this for the official wallets, we will consider implementing it.
