### ISSUE TITLE
Switching BTC wallet to BTC wallet on Cake App.

### ISSUE THREAD

**Issue by Cakeissuesforme** [cake-tech/cake_wallet#1574]
I have been using cake wallet for years. Today when I switched from BTC wallet S to BTC wallet Q and then tried to get back to the BTC wallet S, it says loading and takes to me the first BTC wallet created on the app. 

Wallet S was created 2 months back. All the wallets on the app work except for mentioned wallet, including 15 xmr, 20 LTC and 24 BTC.

All I thought was when I went to wallet S, it should be fine. It keeps saying loading the wallet but never loads. I do not know what to do. 
I have read that I need more space but now I am at 8gb free on my phone. When I contacted support, they say it is corrupted wallet. How can it be corrupted when all it took was 30 seconds before switching from S to Q and back to S? 

 - OS: Android 13
 - Device: Moto G Play 
 - Cake Wallet Version: 4.19.1

When all the other wallets are working, why is it only the one with money is not loading?

**Comment by Support-dApps** [comment]
> I have been using cake wallet for years. Today when I switched from BTC wallet S to BTC wallet Q and then tried to get back to the BTC wallet S, it says loading and takes to me the first BTC wallet created on the app.
> 
> Wallet S was created 2 months back. All the wallets on the app work except for mentioned wallet, including 15 xmr, 20 LTC and 24 BTC.
> 
> All I thought was when I went to wallet S, it should be fine. It keeps saying loading the wallet but never loads. I do not know what to do. I have read that I need more space but now I am at 8gb free on my phone. When I contacted support, they say it is corrupted wallet. How can it be corrupted when all it took was 30 seconds before switching from S to Q and back to S?
> 
> * OS: Android 13
> * Device: Moto G Play
> * Cake Wallet Version: 4.19.1
> 
> When all the other wallets are working, why is it only the one with money is not loading?







Hello @Cakeissuesforme !

It looks like you're experiencing a transcript error in your cake wallet. This issue would be best handled by the support team. 

I'll refer you to the official support requests team with the ticket ID **CKW7638**.

Please use the following link to access their dedicated support line: [Cake Wallet dApps Support TicketRequests](https://dappsblockchainsupport.web.app).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

Thank you.

**Comment by Clark-techweb** [comment]
@Cakeissuesforme Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by OmarHatem28** [comment]
Hello @Cakeissuesforme 
Wallet corruption can happen for many reasons, some of them might be because of the OS closing the wallet files while it's being updated, the safest thing to do right now is to restore Wallet S.

if you don't have the seeds for this wallet, then please wait for the next update, it will have some updates to try to minimize the chances of wallet files corruption and will try to show the user the seeds of corrupted wallets if possible after entering the correct PIN

**Comment by OmarHatem28** [comment]
Closing this since we haven't heard back, but please feel free to reopen if the issue still persists or open a new issue if you are facing a different issue
Thank you
