### ISSUE TITLE
Monero wallet is broken with Cake_Wallet_v4.19.3_224.apk

### ISSUE THREAD

**Issue by R44D44** [cake-tech/cake_wallet#1601]
**Describe the bug**
after updating to Cake_Wallet_v4.19.3_224.apk Monero wallet is broken. 
-wallet seed is empty

**To Reproduce**
1. update to Cake_Wallet_v4.19.3_224.apk
2. open app
3.  read: Monero wallet is broken/-wallet seed is empty
4. let it sync/restart app/reboot fon
5. same issue
6. with older version on other fon no such error

**Expected behavior**
no error

**Screenshots**
![Screenshot_20240813-122713_Cake Walletx](https://github.com/user-attachments/assets/cd9d5909-a8e1-4103-9a5d-623c215de318)

**Platform:**
 - OS: Android 13]
 - Device: poco x3 nfc
 - Cake Wallet Version: 4.19.3_224

**Additional context**

**Comment by preland** [comment]
This also occurs on 4.19.3 on iOS 16.0. That would mean that anyone who updated their app on the App Store could also be facing this issue.

**Comment by R44D44** [comment]
Cake_Wallet_v4.19.4-x86_64.apk (v.225) fixes the bug. thanx.
