### ISSUE TITLE
[Feature Request] Add option to rename or delete contacts, subaddresses and accounts

### ISSUE THREAD

**Issue by dvaupel** [cake-tech/cake_wallet#166]
When keeping a contact, subaddress or account pressed for a little time, the user should be presented with the option to rename or delete the entry. This is a basic feature that is missing at the moment (at least on Android).

**Comment by SamsungGalaxyPlayer** [comment]
# Contacts

- [x] Rename
- [x] Delete

# Subaddresses

- [x] Rename
- [x] Delete (we will not allow deleting)

# Accounts

- [x] Rename
- [x] Delete (we will not allow deleting)
