### ISSUE TITLE
[Linux] wallet sign on screen needs a Cancel button..

### ISSUE THREAD

**Issue by ronohara** [cake-tech/cake_wallet#1678]
### Discussed in https://github.com/cake-tech/cake_wallet/discussions/1677

<div type='discussions-op-text'>

<sup>Originally posted by **ronohara** September 10, 2024</sup>
If you start the Linux cake wallet and you have used a wallet in the past, it offers you a login screen .. but I have broken my install and can not login ... 

I need to Cancel the login just like I can in the normal Monero GUI wallet. At the moment because of my broken installation I can't even restore the wallet from seed words.  I have removed and reinstalled cake wallet, but it has remembered the od wallet name somehow - and I can't see how to erase that wallet completely.

If I select Cancel, it should go to a screen like the normal Monero GUI which then offers you a choice of:

- 
![image](https://github.com/user-attachments/assets/d62b94b2-e58a-4d74-9fc8-97f57fb3d5d7)
</div>

**Comment by ronohara** [comment]
This is the screen that needs a cancel button.

![image](https://github.com/user-attachments/assets/851ff1d1-6f12-490b-8aa2-97312c98c02f)

**Comment by ronohara** [comment]
If I can make my installation completely forget about cake wallet (remove everything) and then start again - and restore the wallet ... that would be a workaround...  but how do you do that,

**Comment by tuxpizza** [comment]
Under ~/.local/share/cake_wallet (Or ~/.var/app/com.cakewallet.CakeWallet/data/cake_wallet/ if using flatpak)
there's a file called "shared_preferences.json"

Open that, and find the field "flutter.current_wallet_name":"Wallet". You can change the "Wallet" part to the name of a different wallet.

And under ~/Documents/cake_wallet/wallets/monero 
You can delete the files of any specific wallet.

**Comment by ronohara** [comment]
Ok ... the file is actually here:    /.local/share/com.example.cake_wallet$ vi shared_preferences.json 

I changed the "flutter.current_wallet_name"  to the wallet I actually want (a BTCwallet) and it lets me sign in. 

But immediately shows a different wallet - an XMR wallet.    There was a brief message about changes to BIP0039 with the current release .. but I didn't read it properly.

If I go into settings and wallet. Then select the BTC wallet I want I get this error message.

![image](https://github.com/user-attachments/assets/ea7dd17a-4358-42d3-86d3-a1c94aaa5907)


If I test the seed words using tools from https://github.com/bluescan/bip39tools  the final seed word given to me when I created the wallet is an invalid checksum.    I can use those tools to find the correct checksum of course.

There is a small amount of BTC in the wallet ... currently inaccessible ... the wallet files themselves are intact.

**Comment by ronohara** [comment]
I will close this and open a bug about the BIP0039 problem

**Comment by ronohara** [comment]
Thie wallet was created using 4.15.3 .. it looks like the transition to BIP0039 wallets breaks existing wallets.

The change is described hereL https://cakelabs.com/news/cake-wallet-adds-bip39/

See more details in https://github.com/cake-tech/cake_wallet/issues/1681
