### ISSUE TITLE
[Linux] 4.19.5 cant open  BTC wallet created by 4.15.3  - Corrupted wallet seeds

### ISSUE THREAD

**Issue by ronohara** [cake-tech/cake_wallet#1681]
![image](https://github.com/user-attachments/assets/f2838429-9fa6-4707-9553-843a029bc24e)

This wallet was created using 4.15.3   ..  it looks like the transition to BIP0039 wallets breaks existing wallets.

The change is described hereL https://cakelabs.com/news/cake-wallet-adds-bip39/

**Comment by ronohara** [comment]
There is also no way to restore a wallet using the electrum style seed words that were used in the earlier release.

**Comment by ronohara** [comment]
I have moved the funds out of that wallet. So now I can share the seed words that are an issue when using Cake wallet 4.19.5  ... they are.

promote arrow sock aisle anchor fog hero lecture jazz fabric still more
debris slide tiny merit ribbon coconut camp current short almost symptom
patient

**Comment by xorblorp** [comment]
Could this be the same issue as https://github.com/cake-tech/cake_wallet/issues/1682?

**Comment by OmarHatem28** [comment]
Hi @ronohara thanks for opening the issue,
Cake Wallet should already support detecting the derivation path automatically, so if you enter a seed that has previous transactions it will automatically detect which derivation path has previous transactions and will use that.

and indeed I tried restoring your wallet seeds and it restored the correct wallet with some transactions in it.

and also if the wallet doesn't have any transaction history, then you can always select whether to use electrum or bip39 derivation paths through the `Advanced Settings Page`

Closing this as resolved, but feel free to reply here if that doesn't answer/solve your issue

@xorblorp Unfortunately it's not related, we are still looking into #1682  issue with Monero seeds tho
