### ISSUE TITLE
Cake Wallet does not create a new receive address for Monero

### ISSUE THREAD

**Issue by xorblorp** [cake-tech/cake_wallet#1683]
**Describe the bug**
Cake Wallet claims to create a new receive address every time inside the app and then reuses the first receive address forever.

**To Reproduce**
1. Click on receive
2. Get a Monero address
3. See how it says that it creates a new address every time, but that old addresses keep working.
4. Send some XMR ot the address.
5. Wait for the XMR to arrive
6. Click on receive again
7. Notice how the address is still the same

**Expected behavior**
Cake Wallet does what it says instead of trying to gaslight me that it's a new address.

**Screenshots**

**Platform:**
 - OS: iOS
 - Device: iPhone
 - Cake Wallet Version: Latest on App Store

**Additional context**

**Comment by tuxpizza** [comment]
This is a known bug, and is being fixed soon!
