### ISSUE TITLE
[Bug] Wallet loses sync status/cache on initial sync if application is sent to background (Android APK)

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#170]
Hey there,

Was just doing a new initial sync of an older wallet, and while about 75% of the way through the sync from restore height I went through some notifications to reply to messages I had received while I was syncing.

When I navigated back via the recent apps to Cake Wallet, the sync had lost it's progress and started from 0% (restore height) again.

If there is any way to capture logs let me know and I will try to reproduce.

Thanks!

More info:

OS - `CalyxOS 2.8.0`
Cake Wallet version - `cake-wallet-4.2.4-55.apk`, `4.2.3` in-app version
Cake Wallet install method - Android APK via Github

**Comment by sethsimmons** [comment]
Side note -- I downloaded `cake-wallet-4.2.4-55.apk` via Github, the latest release, but in-app info still shows `4.2.3`.

**Comment by sethsimmons** [comment]
Another note -- I did *not* disable battery optimizations for Cake, but was not prompted to and didn't think about it until now.

That certainly could have been the cause of the issue, and may be something worth exploring prompting users to do on install.

**Comment by sethsimmons** [comment]
This was still happening in a pre-release of `v4.2.7`, but I have not tested on the official `v4.2.7` release yet.

**Comment by jtgrassie** [comment]
Perhaps relevant for anyone wishing to fix this issue: https://medium.com/stuart-engineering/keep-flutter-running-background-on-android-6ffc85be0234

**Comment by SamsungGalaxyPlayer** [comment]
I know the app doesn't allow background syncing, but is it still improperly discarding progress?

**Comment by sethforprivacy** [comment]
In brief testing the wallet seems to properly be keeping the sync alive in the background even after switching through a few other apps, notifications, etc.

Closing as this appears to be fixed!

**Comment by cahlenlee** [comment]
This is definitely not fixed. It's been plaguing me for months, repeatedly causing me to losing hours of sync progress and still occurs on latest (4.12.1, Android 13, Pixel 4 XL).

This is especially bad when paired with frequent crashes during sync, and sometimes the entire sync resetting to 0 after days at Complete.
