### ISSUE TITLE
[Bug] Cannot label the currently selected subaddress

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#172]
In trying to set labels for subaddresses I use regularly, I noticed that you cannot label a subaddress if you have it selected, but can label unselected subaddresses.

This makes it extremely tricky to label specific addresses ATM.

See the video below for the bug:

https://user-images.githubusercontent.com/40500387/129077690-ccef52f2-39b4-4cca-8888-63243dceeb96.mp4

**Comment by SamsungGalaxyPlayer** [comment]
https://github.com/cake-tech/cake_wallet/pull/291
