### ISSUE TITLE
[Feature] Provide setting to hide/disable exchange and buy portions of Cake Wallet

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#174]
This request is absolutely not necessary and just a nice to have, but for those of us that don't want to use the exchange/purchase functionality within Cake Wallet it would be great to be able to disable and/or hide those features via the apps settings, making the "Send" function the only bottom bar function available (and perhaps even enlarging it to fill more of that space).

Again, definitely not necessary, just something I would personally find useful :)

**Comment by SamsungGalaxyPlayer** [comment]
This is not something we currently plan to support. A bottom button redesign is coming however that should make these icons appear less cluttered.
