### ISSUE TITLE
Cake_Wallet_v4.19.5_Windows - Not auto generating sub addresses

### ISSUE THREAD

**Issue by justatypicaluser** [cake-tech/cake_wallet#1746]
Hi all .

Cake_Wallet_v4.19.5_Windows

Auto generate sub addresses - ENABLED

When i am in Cake_Wallet_v4.19.5_Windows and on my Monero wallet, i press recieve. The address given to me is NOT a sub address (beginning with an 8), it is still a main address (beginning with a 4).

In order to regenerate the address i send a payment to the account.
I press recieve again - the next addresss is still NOT a sub address. It is still a main address beginning with 4.

Auto generate sub address - DISABLED
I go back to my Monero wallet. 
When i press recieve, i then get an option to manually create a sub address.... ONLY THEN does it it give me a sub, starting with an 8.

So, if i have to keep manually creating sub addresses for recieving payments - my address book gets longer and longer. 
Once used, the old sub address are also not able to be deleted from the address book. 

So i am asuming it is software error unless im missing something?

Surely pressing recieve in my Monero account on Cake_Wallet_v4.19.5_Windows, should generate a sub address, then all sub address payment transactions display in the main account transaction list - without creating a long and growing, un deleatable address book?

Finally standard seed length in CakeWallet is polyseed 16 - is there any need in using a 25 word long seed, besides being able to be recoverable in GUI Wallet - as many other wallets offer 12 word seed so surely 16 is more than ample??

I would appreciate your time to respons and discuss. 
Thanks in advance.

**Comment by tuxpizza** [comment]
This is already fixed in 4.20, which will be releasing soon

**Comment by tuxpizza** [comment]
On the comment of the 16 word Polyseed, this is a newer type of seed phrase that offers the advantage of embedding a sort of wallet "birth date" / blockheight in the seed itself.  16 is more than fine in this case, so I wouldn't worry about it in terms of security. You can retrieve the "legacy" 25-word seed phrase from the Security and backup page if you want to later restore in Monero GUI or any wallet that only uses legacy. Hope this helps!
