### ISSUE TITLE
Silent payment scanning doesn't work on BTC Testnet

### ISSUE THREAD

**Issue by turbolay** [cake-tech/cake_wallet#1792]
![CleanShot 2024-11-06 at 08 22 50@2x](https://github.com/user-attachments/assets/b037534b-202a-447c-b18c-caaaf0dda9ae)

It is always stuck on "Starting Scan"

**Comment by hot-bott** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@turbolay 
Support.
