### ISSUE TITLE
[Feature] Show subaddress label (where available) on the transaction history page/transaction details page

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#183]
Pretty straightforward, but would be very nice to have the label of the receiving subaddress listed on the transaction history page and the transaction details page.

For example, I have two unique subaddresses used for different donations, and it's very difficult to tell transactions to them apart on the transaction history page unless I memorize the subaddress in full myself.

**Comment by SamsungGalaxyPlayer** [comment]
Done: https://github.com/cake-tech/cake_wallet/pull/333

**Comment by sethforprivacy** [comment]
> Done: #333

Damn, that's a huge improvement! Thanks so much.
