### ISSUE TITLE
[Bug/Feature] Hide available balance unless pressed in the Send screen when balances are set to hidden in settings

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#184]
Hi again,

When recording a quick demo of Cake Wallet, I noticed that even if you have balances set to "Hidden" in the settings, your available balance is displayed clearly in the "Send" screen under the amount field. While I understand that the user needs to be able to easily see available balance to know how much can be spent, IMO that should be hidden unless pressed.

Could do something like "Available balance: TAP TO REVEAL" or similar, or just add in a "Street Mode" that hides balances in every aspect of the app completely.

**Comment by SamsungGalaxyPlayer** [comment]
https://github.com/cake-tech/cake_wallet/pull/266
