### ISSUE TITLE
2FA reset after restart the app

### ISSUE THREAD

**Issue by coxde** [cake-tech/cake_wallet#1845]
**Describe the bug**
2FA works once set, but when I close and reopen the app, it seems it was never set (would suggest I set a new 2FA)

**To Reproduce**
1. Go to 'Security and backup/Setup Cake 2FA', follow the process
2. Close the app and open it again
3. Go to 'Security and backup', 'Setup Cake 2FA' would show up again instead of 'Modify Cake 2FA'

**Platform:**
 - OS: Arch Linux x86_64
 - Cake Wallet Version: 4.21.0

**Additional context**
Installed via [AUR](https://aur.archlinux.org/packages/cake-wallet-bin).
Also,in  'Security and backup', 'Require PIN' does not work and would also reset to '10 minutes' after restart regardless of the modify.

**Comment by tuxpizza** [comment]
2FA will be removed soon from Linux as it doesn't provide real security anyways, as the 2FA value is stored in plaintext in a preferences file. (Due to the design this is not an issue for mobile like it is on Linux version)
