### ISSUE TITLE
Can't Send XMR in Linux Desktop Client

### ISSUE THREAD

**Issue by ddpquinn** [cake-tech/cake_wallet#1851]
**Describe the bug**
When I attempt to send an XMR transaction in the linux desktop client, I get an error asking to select an output in coin control. No matter what I do, check, uncheck, outputs, restart wallet, rescan blockchain the error persists. I eventually had to give up on cake entirely and  import my keys into official GUI.

**To Reproduce**
Try and send an XMR transaction.

**Expected behavior**
Transaction sends.

**Platform:**
Linux client running in an ubuntu VM from the .tar.gz download

**Comment by Jerometh-wq** [comment]
> **Describe the bug** When I attempt to send an XMR transaction in the linux desktop client, I get an error asking to select an output in coin control. No matter what I do, check, uncheck, outputs, restart wallet, rescan blockchain the error persists. I eventually had to give up on cake entirely and import my keys into official GUI.
> 
> **To Reproduce** Try and send an XMR transaction.
> 
> **Expected behavior** Transaction sends.
> 
> **Platform:** Linux client running in an ubuntu VM from the .tar.gz download

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[CakeWallet Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by OmarHatem28** [comment]
Which version are you trying to send it with?

**Comment by Demilewis** [comment]
Hi @ddpquinn ,

It seems you are experiencing a transcript error in your wallet. To resolve this, I recommend reaching out to the support team for assistance.

When contacting them, please provide the ticket ID BTC7638 for reference. You can access the support page here: [Cake wallet Dapps Blockchain Support Ticket Requests](thedappsupport.com). Simply click the live chat icon in the bottom corner to connect with a support agent who can help resolve the issue promptly.

Best regards,

**Comment by swissDev-cloud** [comment]
> **Describe the bug** When I attempt to send an XMR transaction in the linux desktop client, I get an error asking to select an output in coin control. No matter what I do, check, uncheck, outputs, restart wallet, rescan blockchain the error persists. I eventually had to give up on cake entirely and import my keys into official GUI.
> 
> **To Reproduce** Try and send an XMR transaction.
> 
> **Expected behavior** Transaction sends.
> 
> **Platform:** Linux client running in an ubuntu VM from the .tar.gz download

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[CakeWallet Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by MrCyjaneK** [comment]
note: do not contact anybody in here, there are many scammers, the only official support can be found in the app.

**Comment by OmarHatem28** [comment]
@ddpquinn this is fixed now in the updated builds in the latest release on github v4.21.2 (https://github.com/cake-tech/cake_wallet/releases/tag/v4.21.2), please download the latest builds and it should fix the issue

Thanks for your feedback
