### ISSUE TITLE
Cake Swap is TRASH that DOES NOT WORK

### ISSUE THREAD

**Issue by happeeshopper** [cake-tech/cake_wallet#1852]
**Describe the bug**
Cannot swap BTC to XMR because of TRASH BUGGED OUT SOFTWARE

**To Reproduce**
 TRY TO TRADE BTC TO XMR

**Expected behavior**
TRADE TO GO THROUGH

**Screenshots**

![1](https://github.com/user-attachments/assets/275f980f-1137-45e1-836b-309431891429)
![2](https://github.com/user-attachments/assets/97a70e1a-d2f1-41b7-b317-f2cb1d681bd8)
![3](https://github.com/user-attachments/assets/116d7cfe-7787-4211-9994-ee9ccae5f8e0)

**Platform:**
 - OS: MXLinux 23.4
 - Device: Desktop
 - Cake Wallet Version: 4.21.2

**Additional context**
WHAT A CROCK OF UNRELIABLE, UNUSABLE SHIT!!!!

**Comment by ancoredev-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Cake Wallet SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by OmarHatem28** [comment]
Hi @happeeshopper , this bug is solved and you can download the latest Linux build from the Releases (https://github.com/cake-tech/cake_wallet/releases/tag/v4.21.2) and you should be able to send and exchange normally
Thanks for your feedback

**Comment by happeeshopper** [comment]
I am already using that version!!!!! I only downloaded it TODAY!!!!

WHERE ARE MY COINS YOU THIEF?????
