### ISSUE TITLE
p2pool support in Cake Wallet

### ISSUE THREAD

**Issue by SChernykh** [cake-tech/cake_wallet#186]
Currently Cakewallet doesn't see [p2pool](https://github.com/SChernykh/p2pool) payouts, this was fixed in Monero CLI/GUI v0.17.2.3. For more details, see https://github.com/monero-project/monero/pull/7894

**Comment by tannerdsilva** [comment]
The development team is working on including the updated Monero libraries in the next update.

**Comment by sethsimmons** [comment]
Testing support in https://github.com/cake-tech/cake_wallet/releases/tag/v4.2.7.

**Comment by sethsimmons** [comment]
Nevermind, the v4.2.7 release notes were edited to remove the version bump line, so I guess it does not include the new version.

Email notification said:

Updated monero lib to v0.17.2.3
Added some build scripts for iOS

Github release now just says:
Added some build scripts for iOS

**Comment by tannerdsilva** [comment]
The dev team deleted tag `v4.2.7` for stability concerns.

**Comment by sethsimmons** [comment]
Testing https://github.com/cake-tech/cake_wallet/releases/tag/v4.2.7 with updated libs.

**Comment by sethsimmons** [comment]
Validated that v4.2.7 works properly with p2pool payouts 🎊
