### ISSUE TITLE
[Feature] Scan invoice QR Codes of BTC / BTCln - Pay with XMR

### ISSUE THREAD

**Issue by benhall847** [cake-tech/cake_wallet#187]
Allow users the ability to scan invoice QR Codes of BTC or BTCln (lightning network)
& pay via XMR.

This would be similar to any swap but at a 'fixed rate' so the BTC received as payment is the correct amount specified.

Of course XMR users would have the expense of the swap + transaction fees.

This would be such an incredible feature that would make paying BTC w/ XMR so much easier!!

This would be a very unique QoL improvement to XMR and make the wallet even more competitive. (:

fixedfloat has been my favorite swap exchange as they support BTCln which in return makes the transactions dirt cheap & basically instant.

**Comment by proudmuslim-dev** [comment]
Seconded, I'd love to see this

**Comment by SamsungGalaxyPlayer** [comment]
Fixed rates are now available for converting XMR to BTC in the Exchange pane of Cake Wallet and Monero.com.
