### ISSUE TITLE
[Bug] App won't launch

### ISSUE THREAD

**Issue by Schopenberg** [cake-tech/cake_wallet#188]
When I open the app, the screen says, 

Error:
HiveError: This should not happen. Please open an issue on GitHub.

![image](https://user-images.githubusercontent.com/14102299/133485258-ec2d737b-48e6-4e05-a8a6-6f03f513c42a.png)

**Comment by SamsungGalaxyPlayer** [comment]
Does this issue persist?

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191
