### ISSUE TITLE
 "Error Corrections and Improvements to Solana's Documentation"

### ISSUE THREAD

**Issue by Nataalabashir** [cake-tech/cake_wallet#1883]
Dear Solana Team,

I'm Nata'ala Bashir Kurawa, and I'm excited to contribute to the Solana ecosystem. I've reviewed the Solana overview and identified some errors and corrections (attached below).

I believe my corrections can help improve the accuracy and clarity of Solana's documentation. I'm eager to collaborate with the Solana team to ensure the platform's continued success.

Thank you for considering my contributions. I look forward to the opportunity to work together.

Best regards,
Nata'ala Bashir Kurawa

Solana Address: H8AJW9VUv5jgZ5RGeJZMTohYiGzfsTzu5bvAnPaJCec7
Email: nataalabashirkurawa@gmail.com
Phone Number: +2349072300190

Error Corrections:

1- Introduction: Solana is a decentralized, open-source blockchain platform. _(Missing: mention of fast and scalable)_
2- Consensus: Solana uses a novel consensus algorithm called Proof of History (PoH). _(Incomplete: missing explanation of PoH) and its use of verifiable delay functions (VDFs).
- Block Time: 400 milliseconds _(Incorrect: block time is 400-800 milliseconds)_
3- Tokenomics: Token Name: Solana (SOL) Total Supply: 200 million SOL _(Incorrect: total supply is approximately 489 million SOL)_
4- Roadmap: Mainnet Launch: Solana's mainnet was launched in March 2020. _(Outdated: roadmap has progressed since mainnet launch)_
5- *Use Cases*: Highlight DeFi, gaming, and social media applications.
6-Blockchain Architecture*: Clarify the roles of Validator, Leader, and Replica nodes.

**Comment by OmarHatem28** [comment]
Hi @Nataalabashir,
I believe you wanted to open this issue on the Solana project,
this is Cake Wallet repo, a non-custodial cryptocurrency wallet app,
we are continuously looking for enhancements for the Solana wallet, so once they implement your ideas, we will be sure to adopt them in Cake Wallet
In the meantime, I will close this, but feel free to open a new issue if you face any issues with Cake Wallet

**Comment by Nataalabashir** [comment]
Okay, thanks Mr Omar
