### ISSUE TITLE
Import of cake wallet backup doesn't work on GrapheneOS

### ISSUE THREAD

**Issue by Peter4487** [cake-tech/cake_wallet#189]
Hello,
I am observing a crash on GrapheneOS when trying to import a backup. To reproduce:

1. Run GrapheneOS (no Google Play Services)
2. Open cake wallet
3. Tick "Agree to terms of use" and click "Accept"
4. Click "Restore Wallet"
5. Select "Restore from backup"
6. Click "select backup file"
7. Select a backup file in the file picker
8. Observe that the app has crashed and re-started. You are on the Terms and conditions screen again.

Entering the password first and then selecting the file results in the same behavior.

**Comment by Morelcia** [comment]
Not everyone has access to phone with GrapheneOS, it would be very useful if you could record logs with `adb logcat` and upload them somewhere

**Comment by BraINstinct0** [comment]
GrapheneOS currently runs on select Pixel phones only, and IIRC since they're essentially hypervisor-level, won't run on VMs. So providing logs will be the only (reasonable) way to get support.

**Comment by Peter4487** [comment]
Here are some logs that hopefully will be helpful. Thank you for your efforts
[cake_wallet_import_fail2.txt](https://github.com/cake-tech/cake_wallet/files/7763380/cake_wallet_import_fail2.txt)
.

**Comment by SamsungGalaxyPlayer** [comment]
Does this issue persist?

**Comment by Peter4487** [comment]
Is there a way to invoke the restore dialog without wiping everything? I ask because any monero wallet will take a long time to sync if starting from scratch, and there isn't a way to make it happen in the background as far as I know

**Comment by SamsungGalaxyPlayer** [comment]
@Peter4487 no, not currently. The best option is to send funds to a new wallet seed if possible to just sync that wallet.

**Comment by Peter4487** [comment]
This was due to "Don't keep activities" being set to True in Developer Options on Android. Was not specific to GrapheneOS. Closing.
