### ISSUE TITLE
HiveError

### ISSUE THREAD

**Issue by travisrobinson** [cake-tech/cake_wallet#191]
App won't open, only displays a white page with the follwing error text:

"Error
HiveError: This should not happen. Please open an issue on Github."

![Screenshot_20210927-065700](https://user-images.githubusercontent.com/19978685/134896383-29987ee8-166a-487c-9c46-ef2257fef491.jpg)

The device is a Samsung Galaxy Tab S6 on Android 11

**Comment by RobertS6A** [comment]
I also received the hive error on my Oneplus 5 with /e/ OS Android 10. I'll reinstall the app later and see if it fixes the error for me. 

![Screenshot_20211108-143328_Cake_Wallet](https://user-images.githubusercontent.com/49530442/140830632-22bae79c-74a7-45be-9145-88b2036c0e2d.png)

**Comment by Pissedpenguin** [comment]
Same here
On pixel 6 pro
![Screenshot_20220414-005016](https://user-images.githubusercontent.com/17756382/163316334-c267aa72-c167-45ca-aebe-715c97ff7277.png)

**Comment by CharlieDixon** [comment]
Same error iPhone 13 iOS 15.5

**Comment by timos22** [comment]
I've just had same issue happen to me on Android before I got a chance to write down seed. Is there any way to recover the wallet?

**Comment by loafing** [comment]
same hive error on iPhone xr  
  How do we fix this error?

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet

**Comment by SamsungGalaxyPlayer** [comment]
@travisrobinson @RobertS6A @JoeCoinz @CharlieDixon @timos22 

Does this persist with 4.5.0?

**Comment by CharlieDixon** [comment]
> @travisrobinson @RobertS6A @JoeCoinz @CharlieDixon @timos22 
> 
> 
> 
> Does this persist with 4.5.0?

I have the latest update on iOS and it's still showing the same error

**Comment by SamsungGalaxyPlayer** [comment]
@CharlieDixon can you try a fresh install?

**Comment by CharlieDixon** [comment]
@SamsungGalaxyPlayer It is no longer showing the error after a fresh install
