### ISSUE TITLE
Linux: titlebar says "cake_wallet"

### ISSUE THREAD

**Issue by ThatOneCalculator** [cake-tech/cake_wallet#1910]
**Describe the bug**

The application's titlebar says "cake_wallet" when it should be something like "Cake Wallet"

**Screenshots**

![image](https://github.com/user-attachments/assets/f0279d35-16a1-4d7c-a7e4-998109892664)

**Platform:**
- OS: Arch Linux x86_64
- Cake Wallet Version: 4.22.0

**Comment by Jason-Tariq** [comment]
Hello @ThatOneCalculator  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
