### ISSUE TITLE
F-Droid repo down

### ISSUE THREAD

**Issue by theo546** [cake-tech/cake_wallet#1914]
**Describe the bug**
The fdroid.cakelabs.com F-Droid repo is currently down and is preventing anyone from updating the app.

**To Reproduce**
1. Access fdroid.cakelabs.com
2. Get greeted with a timeout

**Expected behavior**
The repo should be accessible and should be possibly added to an F-Droid Android client

**Comment by sethforprivacy** [comment]
Hi theo,

Unfortunately we ran into some major issues with the way F-Droid self-hosted repos work that broke our setup completely, and we had very little usage so we decided to simply deprecate the self-hosted repo entirely and point people to other, often better, options. More info:

https://x.com/tuxpizza/status/1864163170123665746

**Comment by Justxd22** [comment]
@sethforprivacy can you check gitlab

**Comment by sethforprivacy** [comment]
> @sethforprivacy can you check gitlab, where can i reach out for a chat?

https://sethforprivacy.com/about/#how-to-contact-me

**Comment by theo546** [comment]
> Hi theo,
> 
> Unfortunately we ran into some major issues with the way F-Droid self-hosted repos work that broke our setup completely, and we had very little usage so we decided to simply deprecate the self-hosted repo entirely and point people to other, often better, options. More info:
> 
> https://x.com/tuxpizza/status/1864163170123665746

Would it be possible to volunteer to host for Cake Labs the F-Droid repo?
I think losing this repo is unfortunate and I'd be happy to take the responsibility for it if possible

**Comment by sethforprivacy** [comment]
Not right now as that would introduce a lot of trust outside of Cake, but I'll keep that in mind for the future!

Thanks for the kind offer :smile:

**Comment by theo546** [comment]
> Not right now as that would introduce a lot of trust outside of Cake, but I'll keep that in mind for the future!
> 
> Thanks for the kind offer 😄

That's understandable, if you can find a way to make this happen you can count on me!
Thank you again for the efforts you and your team made so far!

**Comment by silmarine** [comment]
> Hi theo,
> 
> Unfortunately we ran into some major issues with the way F-Droid self-hosted repos work that broke our setup completely, and we had very little usage so we decided to simply deprecate the self-hosted repo entirely and point people to other, often better, options. More info:
> 
> https://x.com/tuxpizza/status/1864163170123665746

Lots of cake sites need to be updated if this is permanent. I'm new to cake wallet and all over the website and the official guides it says there's an official fdroid repo.
