### ISSUE TITLE
Implement 14-Word Feather-style Wallet Seed with Embedded Restore Height

### ISSUE THREAD

**Issue by CryptoGrampy** [cake-tech/cake_wallet#195]
Hi Cake-

There was a discussion today in the Monero Research Lab about seed phrases that can replace the need for users having to remember block restore heights/dates, and it turns out Feather Wallet already gives users this option by default- a 14 word backup seed- when creating a new wallet (you can also restore a 14 or 25 word wallet in feather).  

Restore heights/dates are confusing to most people and can cause a lot of frustration (as well as Cake issue tickets) when one restores a wallet and the funds don't show up.  Defaulting the Cake wallet to a 14-word seed as implemented in Feather (while also allowing 25 word restoring) would be awesome, create a better user experience, alleviate frustration/issue tickets and allow for simplification of the UI. 

[Feather Wallet Seed Scheme](https://docs.featherwallet.org/guides/seed-scheme)

**Comment by SamsungGalaxyPlayer** [comment]
We don't currently plan to switch to the 14 word version by default, but allowing restoring from these seeds is on the list.

**Comment by SamsungGalaxyPlayer** [comment]
@CryptoGrampy do you know if the GUI or CLI support restoring from polyseed yet? We plan to switch to polyseed as the default when restoring from it is available.

**Comment by CryptoGrampy** [comment]
I think we just need to get the ball rolling again.  Polyseed has been around for nearly a year now.  

https://github.com/monero-project/monero/issues/6639#issuecomment-1299424960

**Comment by sethforprivacy** [comment]
Any updates on this @SamsungGalaxyPlayer? Would love to be able to restore/use Polyseed wallets in Cake Wallet/Monero.com!

**Comment by SamsungGalaxyPlayer** [comment]
https://github.com/cake-tech/cake_wallet/pull/1109

**Comment by tuxpizza** [comment]
Closed since Pollyseed is now available :)
