### ISSUE TITLE
Option to disable PIN Prompts

### ISSUE THREAD

**Issue by kevATin** [cake-tech/cake_wallet#200]
The app constantly asks for the PIN every time you switch from one app to another, and also when switching between wallets. Some might need this degree of security but it gets annoying real quick.

I suggest adding the following yes/no-options:

- Require PIN on wallet switch
- Require PIN on app access (when switching between multiple apps, require PIN every time the app is brought into the foreground)
- Require PIN on app open (if the app is not yet running or hasn't been in the foreground since more than 5 minutes.

**Comment by nahuhh** [comment]
> The app constantly asks for the PIN every time you switch from one app to another, and also when switching between wallets. Some might need this degree of security but it gets annoying real quick.
> 
> I suggest adding the following yes/no-options:
> 
> - Require PIN on wallet switch
> - Require PIN on app access (when switching between multiple apps, require PIN every time the app is brought into the foreground)
> - Require PIN on app open (if the app is not yet running or hasn't been in the foreground since more than 5 minutes.
> 
> 

I agree there should be a way to keep it from locking immediately, and a way to unlock all wallets at once. 

A setting to 

"Lock after"
With options for 

Immediately (default)
Screen off
Timeout 
App close


Perhaps remaining unlocked will remedy the issue of disconnecting on the send screen, forcing you to abandon the transaction.

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/201
