### ISSUE TITLE
Allow quicker switching between Wallets

### ISSUE THREAD

**Issue by kevATin** [cake-tech/cake_wallet#201]
Switching around between multiple wallets is quite tedious right now.
You have to click on the menu button, the wallets button, your wallet of choice, and then confirm that you want to change to that wallet, followed by having to type the PIN.

I believe it would make more sense to have the list of wallets visible on the main screen at all times, possibly in the shape of a horizontally scroll-able row on the very top of the app. And with a simple press onto the wallet you could switch between them.

**Comment by SamsungGalaxyPlayer** [comment]
Thanks for the feedback! We have no plans to add this but we will consider it and keep your use-case in mind.

**Comment by SamsungGalaxyPlayer** [comment]
We plan to allow for a PIN timeout to address the largest annoyance.
