### ISSUE TITLE
Unstoppable domains L2 polygon

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#202]
![Screenshot_20211130_111019.jpg](https://user-images.githubusercontent.com/50635951/144084284-317d662f-5a07-4bfc-9faa-67fe1d6d5cf8.jpg)

Doesn't seem to be working with domains minted on polygon. 

Update incoming?
Thanks

**Comment by nahuhh** [comment]
@mkyq 

Latest version closes this. Thanks!

**Comment by SamsungGalaxyPlayer** [comment]
Now works on both Cake Wallet and Monero.com.
