### ISSUE TITLE
There are a lot of errors here. What should I do

### ISSUE THREAD

**Issue by wkgcoin-project** [cake-tech/cake_wallet#203]
There are a lot of errors here. What should I do.Many documents are missing.
<img width="1082" alt="error" src="https://user-images.githubusercontent.com/73333218/145402289-587fdb6c-0552-4e58-93da-b7d0bfb7cc35.png">

**Comment by mkyq** [comment]
Exactly this issue from your provided screenshot can be produced because need to generate files for mobx stores. For do that please run `flutter packages pub run build_runner build --delete-conflicting-outputs`. Please make sure that you have loaded all dependencies for the project before run it.
