### ISSUE TITLE
Android nodes appear as red even if available

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#204]
This one has been a problem for a while, but right now the node tab always shows all nodes as red (down) and any manual "Test" fails immediately.

The nodes still work, but the testing functionality seems entirely broken.

**Comment by mkyq** [comment]
Please provide for what wallet's type you get this issue.

**Comment by sethforprivacy** [comment]
Monero, that's all I use Cake for.

**Comment by mkyq** [comment]
Cake monero node is red for you too ? Maybe do you use node with auth and they are red for you ?

**Comment by sethforprivacy** [comment]
All nodes show as down, even the default Cake nodes.

All three of the non-default nodes are working perfectly and pass all of my own status checks outside of Cake. None of the nodes use auth of any kind.

![signal-2021-12-17-103923](https://user-images.githubusercontent.com/40500387/146569822-80d369cf-56b1-4847-b866-ba04f7e5b3e9.jpeg)

**Comment by nahuhh** [comment]
> Cake monero node is red for you too ? Maybe do you use node with auth and they are red for you ?

I came here to see if someone had already posted the issue. 

Also, when you add a node and tap "test", the test fails immediately. Even though the node works

All nodes show red.

**Comment by sethforprivacy** [comment]
> > Cake monero node is red for you too ? Maybe do you use node with auth and they are red for you ?
> 
> I came here to see if someone had already posted the issue.
> 
> Also, when you add a node and tap "test", the test fails immediately. Even though the node works
> 
> All nodes show red. ![Image_4.jpg](https://user-images.githubusercontent.com/50635951/146629205-504b7fd8-453d-41e8-9a9f-4cdc83bb906f.jpg)

Yes, same experience for me as well. Hopefully an easy fix :)

**Comment by sethforprivacy** [comment]
@mkyq note that this is still a problem on the latest versions of Cake and Monero.com.

**Comment by SamsungGalaxyPlayer** [comment]
We've been unable to fix this for android. It's fixed in iOS. We'll keep looking.

**Comment by nahuhh** [comment]
If it helps, it does seem to works for Bitcoin nodes on android.

**Comment by SamsungGalaxyPlayer** [comment]
This is fixed in Cake Wallet 4.5.0 / Monero.com 1.2.0
