### ISSUE TITLE
Update project to include build instructions for iOS

### ISSUE THREAD

**Issue by deverickapollo** [cake-tech/cake_wallet#207]
Currently, the repo does not provide build instructions for iOS.  Can we update the project to include a README detailing build instructions similar to what is available for android [here](https://github.com/cake-tech/cake_wallet/blob/main/howto-build-android.md)?

Thanks team!

**Comment by SamsungGalaxyPlayer** [comment]
Are the new instructions sufficient?

**Comment by VladimirVasic994** [comment]
Hello, unfortunately I have a problem building the app with new instructions since there I guess are some scripts and folders missing :). Maybe some files are not commited on ios_build_howto branch?

Thank you

**Comment by emanuelb** [comment]
There is documentation in open MR at: https://github.com/cake-tech/cake_wallet/pull/213/files#diff-bd3037483c933283e8629c01582df685b47b5357b192e90151976bb07d3dc008

issue can be closed as it's duplicate, there older issue about iOS build instructions that I opened at: #114 and newer duplicate at #479
