### ISSUE TITLE
[Bug] All nodes fail tests on Android

### ISSUE THREAD

**Issue by Kia678** [cake-tech/cake_wallet#210]
used Cake Wallet v4.27 for android

All nodes fail tests and show as down(red), including cake's own node. For those nodes that require authentication, even if I fill in the correct username and password, the test still fails.

More than one person has reported this bug, hope to fix it in next version.

In addition, please consider updating the monero core to 0.17.3.0

**Comment by mkyq** [comment]
Thanks for your feedback. Unfortunately I'm not sure that we will fix it in next version, but I will put it in our list. For now we are focused on monero only app by cake wallet.

**Comment by nahuhh** [comment]
Main issue is dup of #204

Unsure about 0.17.3.0
