### ISSUE TITLE
How to run project on Windows

### ISSUE THREAD

**Issue by mihajlovicnemanja** [cake-tech/cake_wallet#231]
Hi I tried to run project on Windows 10, and tried to follow your instructions given in description but could not run the project.
Can you please help me.
Thank you in advance

**Comment by juanpc2018** [comment]
CakeWallet for Android and iOS = you need Andriod Emulator, there are plenty...
Avoid Android x86, you need ARM emulator.
NOX for OSX is nice. Maybe has Windows.
Google has Another Emulator for developers.
Etc...

**Comment by SamsungGalaxyPlayer** [comment]
If you need additional help, please email support@cakewallet.com. Thanks!
