### ISSUE TITLE
Works well so far but...

### ISSUE THREAD

**Issue by juanpc2018** [cake-tech/cake_wallet#232]
When scanning blocks, sometimes crash and exit.
No harm done, just open again, type password, and continues to sync.
Could be node.too slow?

Android 9.

The only strange thing... So far.
When i was Restoring a.Wallet,
Automatically selects passphrase / Mnemonic
But i want to restore from keys.
Swiping works ok, but...
Not easy to guess.
Should ask first what i want.
Or should have arrows to indicate swipping action..

**Comment by SamsungGalaxyPlayer** [comment]
Thanks for using Cake Wallet! If you have support questions, please email support@cakewallet.com. They are happy to help you out.
