### ISSUE TITLE
[Feature Request] Hide Used Sub-Addresses

### ISSUE THREAD

**Issue by tasty-water** [cake-tech/cake_wallet#263]
I use a different sub-address nearly every time I transact with Cake Wallet/Monero.com

Due to this, I end up with plenty of poorly named sub-addresses.

I think a useful feature would be the ability to:
- In Settings, a "Hide all used sub-addresses" option which is disabled by default.
- Hide selected sub-addresses by swiping, similar to how you can edit a sub-address label by swiping.
- A "Show/Hide used sub-addresses" toggle in the address selection screen.
- Generate random sub-address labels similar to how wallet names can be randomly generated.

**Comment by nahuhh** [comment]
I think 3 changes should be ok


1. Setting to "Autorotate and use subaddress by default"
Auto hidden after use, ability to show all (including hidden) and ability to restore. Restore is essentially #2
2. When this setting is enabled, you can pin the current/next subaddress. Restoring a used subaddress will also pin it.
Unpinning will hide the address if it has been used.

When autorotate is off = default behavior + the ability to swipe to hide the address and the button to show and restore previously hidden addresses

Also don't mind the autonaming, but would like it to be deterministic. Meaning, the address will always give the same name (so if I restore, names arent "lost")

**Comment by SamsungGalaxyPlayer** [comment]
Auto subaddresses are now available as the default, which should address this use-case.
