### ISSUE TITLE
QR Code + Unstoppable domains isssue

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#273]
1. Create qr code for a domain [monero.crypto works]
2. Scan with cake wallet
3. Address field is populated with "monero.crypto"
4. Try to send tx. Fails with "wrong crypto type" for address

Workaround
4. Manually selecting the address field, then tap anywhere outside of it will force cw to check

The issue is that it is not checking until after you manually interact with the field.

**Comment by SamsungGalaxyPlayer** [comment]
@hope-with-me can yuo check to see if this issue persists?

**Comment by nahuhh** [comment]
> @hope-with-me can yuo check to see if this issue persists?

Confirmed on 4.4.7
