### ISSUE TITLE
[Feature request] For Android, use a background service for wallet sync

### ISSUE THREAD

**Issue by intr-cx** [cake-tech/cake_wallet#275]
I don't know if this is possible on iOS, but for Android it would be a big UX improvement if Cake could sync your wallet(s) using a background service, so that the app does not need to stay open and awake. Monerujo already implements this, for example. 
This would also open up the possibility for notifications on incoming transactions, as well as better battery life since the screen would not need to stay on with the app opened.

**Comment by nshopik** [comment]
ios can do long background task as well, as long device connected to power
https://developer.apple.com/documentation/backgroundtasks

**Comment by trymeouteh** [comment]
Would like to see this also

**Comment by nshopik** [comment]
Recent release added background sync for ios and android

**Comment by seniorm0ment** [comment]
Should we get a notification when it successfully finishes syncing?

Also I just checked my XMR wallet this morning which I fetched yesterday afternoon, and it shows it was completely out of sync (never finished the initial sync). Once I went into the wallet (not even when I had the app open in another wallet) it showed it was starting syncing.
