### ISSUE TITLE
Coin Control + Generate & Label Addresses for Privacy

### ISSUE THREAD

**Issue by trymeouteh** [cake-tech/cake_wallet#303]
To make privacy easier in Cake Wallet when using non-private cryptos (Which are most cryptos out there) I would like to suggest adding coin control and the ability to easily create new addresses within a wallet. There are a few ways this could be done but I think this is the best and most user friendly approach.

By adding a label feature to label addresses for non-private crypto just as you can for Monero subaddress will help manage addresses for non-private cryptos.

**How it works**

Lets say this is your 12 word seed phrase...

`humor camp fitness whisper duty sort organ betray monkey wait hedgehog network`

The BTC address this will be with the derived path set to "m/44'/0'/0'/0/0" would be...

`1ETs5hXpsEPkNnTnE9zpNvVvpXuPVPsxcc`

The BTC address this will be with the derived path set to "m/44'/0'/0'/0/1" would be...

`1Hw49fABAg9DFxWLtx6Z4SLY5H1dm2LTNq`

The BTC address this will be with the derived path set to "m/44'/0'/0'/0/2" would be...

`12e4WwmdTeCcieHhSmE2Zp5XxqN7wzh6v6`

And so on.

We can call these addresses "sub addresses". When you browse your sub addresses for a certain coin you have these options on managing sub addresses.

- Rename the sub address (Give the sub address a label). If no label is set it will set the label to the derivided path number
- Show/Hide sub address (To be able to hide addresses you no longer use)

**Sub Address Label File**

In the apps setting you will choose a directory on the device on where sub address label file will be stored. This directory will save the sub address labels for each wallet and the app will read this directory for files to determine if you have labels set for certain sub addresses.

A folder will be designated for saving TXT files which will look like the example below. Each file will be named after the address.

_/Wallet 1/Address Labels/Bitcoin (Segwit)/1Hw49fABAg9DFxWLtx6Z4SLY5H1dm2LTNq.txt_
```
McDonalds on Main Street
```
_/Wallet 3/Address Labels/Dash/XjhdSYsh6vrnq86vbCaeiPtX8Z1uqhH929.txt_
```
KFC on 3rd Street
```

Using the seed phrase, this could be used to encrypt the text files and even the text file names making it so other apps or malware cannot determine what addresses you control by seeing the text file names and by seeing the contents of the text files (the labels themselves).

**Import/Export**

Simply you can export all of the files in the "_Address Labels_" folder into a ZIP, GZIP or 7Z file. And be able to import a ZIP/GZIP/7Z file into the app to restore your sub address labels.

**Third Party Backups/Syncing**

Another important feature to this will be syncing/backups of the sub address label files. I strongly suggest having a directory that the user can choose where the sub address label files are stored on a device which gives the users options on how to backup the sub address label files. The user can setup their cloud storage app such as Nextcloud, FileN, etc to do automatic backups of their sub address label files. Users can also use Syncthing to backup and sync the sub address label files between devices.

With how I suggested the file structure to be setup by having a file for every single label, it will take up little space, and reduce conflicts when using third party syncing/backup tools compared to having a file that will store multiple labels in it at once.

**Coin Control**

Coin Control will need to be added to the wallet. Coin Control is a feature were sending an transactions, it will only use one output and never combine two or more addresses to send coins in a outgoing transaction. If Coin Control remains as a setting in the wallet (Coin Control can be disabled or enabled) Then I would like to suggest having it on by default and when turning if off, it will warn the user that with coin control off, your outgoing transactions may use two or more outputs.

**Conclusion**

This is a big feature request but a powerful one for any crypto wallet. Cake Wallet is an amazing privacy focused open source wallet on the market. Most cryptocurrencies are not private due to the traceability of the coins on the transparent blockchains. This feature when used will allow users to use transparent non-private cryptos such as Bitcoin, Litecoin, and any other cryptos added in the future, etc with privacy. To transfer your coins from your main Bitcoin wallet to one of your Bitcoin sub addresses, you do not just send it from "Wallet 1" Bitcoin main to "Wallet 1" Bitcoin sub address 001, you swap from "Wallet 1" Bitcoin to Monero and then swap Monero to "Wallet 1" Bitcoin sub address 001 and then send it out from there.

This feature also shares many similarities to the Offline Transaction Notes. If the Offline Transaction Notes comes to be, it would be amazing to also have offline transaction notes for sub address transactions.
https://github.com/cake-tech/cake_wallet/issues/304

**Comment by nahuhh** [comment]
Why do you spam this on every wallet on GitHub.

**Comment by SamsungGalaxyPlayer** [comment]
Cake Wallet already supports manual coin control for Bitcoin and Litecoin, with allowed selection per output.

It's unrealistic for us to completely prevent all outputs from being merged, since that's just how Bitcoin works. We do what we currently can, which is allow users to select only 1 output (or several) for spending.

We do not have plans at this time to label Bitcoin addresses. Cake Wallet displays a new Bitcoin address for users once they are used, like most other wallets. After that, they are effectively "tossed."

Users can add notes under Coin Control to label each output.
