### ISSUE TITLE
Crashing after google play version update 

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#322]
The lasted update (w/ Haven) isnt posted on GitHub, perhaps a known issue? 
Updated from Google play and app crashes on launch

Update. Fresh install will run, but force close at wallet creation https://user-images.githubusercontent.com/50635951/161373195-12610193-eb3b-404a-96c9-710f91b0f1f9.mp4

![Screenshot_20220402_104928.jpg](https://user-images.githubusercontent.com/50635951/161388714-9fae54a9-4d5a-451a-8b9a-5bc7519b23ec.jpg)

**Comment by nahuhh** [comment]
Fixed

**Comment by juanpc2018** [comment]
there is a war against Crypto..
All Govs.
specially US.
has been anounced many times in Congress sessions, presidential speeches, etc...

i would delete Google Account,
install & Update Apks from other sources.
Huawei AppGallery
APKPure
F-Droid,
apk from developer website or github, gitlab, etc, if available..
Extracting .apk with APK Export or APKPure from other google account / phone without crypto history.
etc...
Don´t use Centralized Traiding websites that require ID, & login with BigTech, etc...

Google apks can be updated with GooglePlay without Google account.
but i don´t like the latest calculator... horrible.
i like version 7.8 (271241277)

my 2 cents.

**Comment by nahuhh** [comment]
There was a bug in the app.
It is fixed.

F-droid inclusion is in the works.
