### ISSUE TITLE
cakewallet 4.3.8.apk does Not install on Android9

### ISSUE THREAD

**Issue by juanpc2018** [cake-tech/cake_wallet#327]
cakewallet 4.3.8 does Not install on Android9, Fail.
monero.com 1.0.4 install ok.
cakewallet 4.2.9 install ok.
cakewallet 4.0.94 install ok.

monero.com 1.0.4 install ok in Android7
cakewallet 4.0.94 install ok.
cakewallet 4.2.9 install ok.

**Comment by juanpc2018** [comment]
monero.com 1.0.5 install ok in Android7
cakewallet 4.4.0 install ok.

cakewallet 4.4.0 does Not install on Android9, Fail.

**Comment by SamsungGalaxyPlayer** [comment]
Please use the latest version.
