### ISSUE TITLE
monero.com 1.0.4 Fail to sync on Android7

### ISSUE THREAD

**Issue by juanpc2018** [cake-tech/cake_wallet#329]
monero.com 1.0.4 sync ok on Android9
in Android7:
software crashes several times during long sync, in both A9 and A7,
The difference:
in A9 remembers where it was and resumes / continues where it left / crashed.
in A7 does Not remember, has amnesia,
if i start to sync from block 1Million, crashes in 30 minutes, or 1 hour,
and starts again from block 1, crashes again, making impossible to sync in A7.

**Comment by juanpc2018** [comment]
monero.com 1.0.5 fail to sync in Android7

**Comment by SamsungGalaxyPlayer** [comment]
Please contact support@cakewallet.com for them to assist you in diagnosing this issue.
