### ISSUE TITLE
secure screen

### ISSUE THREAD

**Issue by ghost** [cake-tech/cake_wallet#340]
Currently, you can record and take screenshots of the app, which isnt very secure. Most banking apps aswell as apps like signal and keepassdx prevent this by having the FLAG_SECURE for all activites. Im not sure if this is possible with flutter, but I think it should be added considering this app contains financial data

**Comment by SamsungGalaxyPlayer** [comment]
I don't think this is a feature we want to add, or at least it should be disabled by default. Will check with the team.

**Comment by Mohit-Joshi-dev** [comment]
@SamsungGalaxyPlayer sure. Thanks for the reply.

**Comment by BobIsMyManager** [comment]
> I don't think this is a feature we want to add, or at least it should be disabled by default. Will check with the team.

What exactly would be the issue if it was enabled by default?

**Comment by SamsungGalaxyPlayer** [comment]
@BobIsMyManager a lot of people like to take screenshots for support and backups. We get a lot of both casual and expert users. Casual users might just take a screenshot of their seed and/or keys.

We also have many people who take screenshots of their receive screen.

**Comment by BobIsMyManager** [comment]
Maybe in the toast that appears when trying to take a screenshot, it can say where to disable it
