### ISSUE TITLE
Bug: Correct XMR but fiat as 0 in Monero.com wallet

### ISSUE THREAD

**Issue by RastalDev** [cake-tech/cake_wallet#347]
**Issue**: The monero.com wallet shows the correct amount of XMR but shows the fiat to be 0.00

**Reproduce**: Open wallet > underneath both the available amount and the full balance in XMR, the equivalent price should be listed at the current exchange rate in a fiat currency of the users choice, instead of showing the correct amount it shows 0.00
App installed from Play store, version 1.0.5, running on Android 11.

**Expected result**: The fiat should be displayed at the current exchange rate for the XMR balance.

**Actual result**: Fiat instead shows 0.00.

**Comment by SamsungGalaxyPlayer** [comment]
Resolved

**Comment by no-usernames-left** [comment]
This is still an issue in v5.7.0.
