### ISSUE TITLE
Exception: internal error: Failed to get height

### ISSUE THREAD

**Issue by Kia678** [cake-tech/cake_wallet#353]
Device: Android 10/ iOS 14
Cake wallet version: 4.4.0
Symptoms:
After clicking the send button on the transfer page, it has been stuck in circles, and it is still circled after waiting for a few minutes, and no confirmation page pops up.
The same is true for clicking the exchange button on the built-in exchange. It has been stuck in the interface of the circle, and no confirmation page pops up.

![image](https://user-images.githubusercontent.com/85081567/165751773-4e0903bb-ee8a-42a1-b442-09ce317f40e9.png)

**Comment by SamsungGalaxyPlayer** [comment]
What remote node are you using? Please try a different remote node.

**Comment by Kia678** [comment]
> What remote node are you using? Please try a different remote node.

The remote node itself is only the official node of cake wallet

**Comment by SamsungGalaxyPlayer** [comment]
@Kia678 does this issue persist?

**Comment by SamsungGalaxyPlayer** [comment]
Closing for now. Please update to 4.5.0, and if it persists, please comment here.
