### ISSUE TITLE
Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by notquiteog** [cake-tech/cake_wallet#356]
App is currently having issues opening at all and I have a wallet I don't have the restore key to, this issue was fixed in
https://github.com/hivedb/hive/issues/263
Solution: update to Hive ^2.0.6 as cake wallet is currently built with 1.4.4+1

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet
