### ISSUE TITLE
Existing wallet inaccessible (at least from UI) when creating new Bitcoin wallet with the same name

### ISSUE THREAD

**Issue by st1064870** [cake-tech/cake_wallet#358]
!!!Reproduction is very easy, please be careful to save your seed or backup your wallet before you proceed!!!

There exists at list a UI bug here because I can select only the new wallet, so at least from UI the old wallet is inaccessible, seed is inaccessible too. Worst case is that the old wallet is overridden. I don't know Dart to dive into this.

EDIT : In case that this is the expected behavior, the user must be warned first!

**Comment by SamsungGalaxyPlayer** [comment]
Please email support@cakewallet.com with your the full details of the error. I can't understand what is wrong with what you have provided here.
