### ISSUE TITLE
4.4.1 templates blank

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#363]
![Image_154.jpg](https://user-images.githubusercontent.com/50635951/170098649-1e64c22d-e538-470b-8001-8b5a1348c0a5.jpg)

**Comment by SamsungGalaxyPlayer** [comment]
This is an issue on Android, not iOS right?

**Comment by nahuhh** [comment]
Hi
Yes. Android.  Unable to test on iOS

Exchange templates appear to be unaffected.
Send screen templates are the issue.

Thanks

**Comment by nahuhh** [comment]
Still broken on 4.4.3

**Comment by SamsungGalaxyPlayer** [comment]
Acknowledged 👍

**Comment by nahuhh** [comment]
@SamsungGalaxyPlayer 

This seems to be due to some change during the upgrade to 4.4.1
A fresh install of 4.4.4 = templates work.

Can anything be done to reset my templates without a fresh install?

**Comment by SamsungGalaxyPlayer** [comment]
Interesting report! Will check :)

**Comment by SamsungGalaxyPlayer** [comment]
Templates currently need to be fixed with a fresh install. @nahuhh @hope-with-me can you check if this issue is carried over to a backup of a messed up template wallet when a backup is created and restored with 4.4.8?

**Comment by nahuhh** [comment]
The backup/restore menu appears to be missing on 4.4.7. I believe it disappeared around the time or the cake pay release.
I have old backups but unsure how to restore / unable to test if issue is carried over

4.4.8 apk is unavailable

**Comment by SamsungGalaxyPlayer** [comment]
Confirmed that the 4.5.0 release candidate fixes this for old installs.
