### ISSUE TITLE
[Feature Request] Add XRP Wallet

### ISSUE THREAD

**Issue by glskep** [cake-tech/cake_wallet#365]
I know you guys must get a lot of currency adding requests, but XRP is one of the best currencies just for its transaction speed alone. If Cake wallet added it I would ditch any other wallet immediately and never look back because it would be the only wallet to support both XMR and XRP that is both open-source and high quality.

**Comment by SamsungGalaxyPlayer** [comment]
No plans at this time, but we support conversions in the exchange with XRP. Thanks for your recommendation!
