### ISSUE TITLE
Blank Haven Transactions history

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#368]
Since update to 4.4.1 the transaction page for Haven shows the dates but not the transactions 

android 10

![Image_165.jpg](https://user-images.githubusercontent.com/50635951/171379546-14cfc13e-3698-4564-b772-1ee91d00dae2.jpg)

**Comment by SamsungGalaxyPlayer** [comment]
https://github.com/cake-tech/cake_wallet/pull/373

**Comment by nahuhh** [comment]
Confirmed fixed
