### ISSUE TITLE
Monero QR URI values should auto populate in transaction 'Notes'

### ISSUE THREAD

**Issue by CryptoGrampy** [cake-tech/cake_wallet#371]
Not sure if this is a bug or intentional, but when scanning an _integrated_ address with recipient_name and tx_description, nothing populates in the 'notes' section of the payment; have not tested this with a main or subaddress.  Would be great to see this field populated similarly to Monerujo and follow the Monero URI format rules: https://github.com/monero-project/monero/wiki/URI-Formatting#wallet-definition-scheme

**Comment by SamsungGalaxyPlayer** [comment]
https://github.com/cake-tech/cake_wallet/pull/466
