### ISSUE TITLE
Cake wallet iOS application issue

### ISSUE THREAD

**Issue by sukhoi30mki** [cake-tech/cake_wallet#375]
My iOS cake wallet application is showing attached error. As I don't have the seed phrase written elsewhere. My tokens will be lost.  

![error](https://user-images.githubusercontent.com/52794156/172617589-2c38e6aa-b23f-4873-93d8-0d0e096a9fd7.jpeg)

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/356
