### ISSUE TITLE
[Feature Request] Add confirmations by pending transactions in the Transactions screen

### ISSUE THREAD

**Issue by satrinity402** [cake-tech/cake_wallet#382]
Would be nice to see how many confirmations (up to 9 confs for Monero) are on a given pending transaction. Monerujo handles this well. That way you can quickly glance at your transaction list and see how close your transaction is to being fully confirmed.

**Comment by SisyphusRising** [comment]
Any update on this? Seems like a pretty valuable yet easy feature to implement.

**Comment by satrinity402** [comment]
cc: @SamsungGalaxyPlayer

**Comment by ChristopherKing42** [comment]
Equivalently you could put the estimated time until confirmation (which indirectly tells you how many confirmations there are). This estimate could be the mean, median, or even a percentile range so users don't get frustrated.

**Comment by nahuhh** [comment]
@tuxpizza close

**Comment by tuxpizza** [comment]
@nahuhh browsing old issues I see :)
