### ISSUE TITLE
Increase QR code to maximize size on receive screen

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#383]
In testing with a General Bytes ATM, Monero.com is unusable as the QR code is too small for the QR reader to detect. Enlarging the QR code by taking a screenshot and zooming in, but no way to use Monero.com directly.

Now that the receive screen is the full page, the QR code should be enlarged to take up as much screen real estate as feasible to help with detection.

**Comment by sethforprivacy** [comment]
After more trial and error it seems that the lines between squares in the QR code format are the issue, not only the size.

Even when you increase the size of a screenshot QR code it's not usable on the BM4 General Bytes ATMs, apparently.

Very odd!

**Comment by SisyphusRising** [comment]
Literally created this account to bring attention to this same issue and found your post. Just making this comment to let it be known it isn't just you. I tried all the same things you did and was unable to detect the QR code.

**Comment by SamsungGalaxyPlayer** [comment]
We are still looking into the "square" issue, but the next release will at least have an ability to make the QR code fullscreen with full brightness.

https://github.com/cake-tech/cake_wallet/pull/390

**Comment by nahuhh** [comment]
The lines between the squares, the color, transparency etc are all style choices.
It is a low correction version 5 qr code. But many readers wont read "special" versions.

Personally I wouldnt be surprised if the issue was the inversion. (The inversion is unnecessary, as cake is just inverting white and black.. the qr essentially looks the same but is harder to read for older readers)

**Comment by nahuhh** [comment]
BTW @sethforprivacy 
This is live in the lastest github version

**Comment by sethforprivacy** [comment]
Looks much better, but I don't have an ATM to test this with -- I would expect it would be fixed though, so will close this out. Thanks!
