### ISSUE TITLE
Cake Wallet is not saving the sync progress

### ISSUE THREAD

**Issue by macruspareto** [cake-tech/cake_wallet#389]
Cake Wallet 4.4.1

I tried to restore and sync one of my older Monero wallets (with last transaction dated Jan 2021).

After 2 hours it was almost done (less than 90k blocks remaining) but due to high CPU load, I think the kernel watchdog killed the Cake process. And after starting it, the sync did not resume from that last known position but from the beginning.

Is it by design or there's some workaround to make it remember an unfinished sync position?
Thanks a lot !

**Comment by lacdael** [comment]
second. 

Nodes surely have a hash map of balances to function. If the XMR community agreed to let users simple know if they had > 1XMR at any one time, that would be a great user experience improvement and would still maintain privacy.
