### ISSUE TITLE
There are problems when running a higher version of flutter

### ISSUE THREAD

**Issue by coloredSky** [cake-tech/cake_wallet#393]
There are problems when running a higher version of flutter.When Flutter version is not 2.0.2.Haven't adapted a higher version of Flutter for too long.

**Comment by SamsungGalaxyPlayer** [comment]
You're right :) We have a task to refactor portions of the code to work with higher Flutter versions. I'm going to close this broad issue. If you have more specific comments on areas of the code for this, feel free to open another issue. Thanks!
