### ISSUE TITLE
[QoL Improvement] Cache output distribution on first sync and update each subsequent sync

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#395]
One of the most annoying user experience issues for me when using any mobile Monero wallet is that when I go to send a transaction for the first time after opening my wallet, it takes multiple seconds (at least) for me to be able to actually send the transaction. Once you've sent a single transaction, and if you keep the wallet open, subsequent transactions are very fast as the output distribution is kept for that wallet session.

After talking to a couple of other Monero developers, it seems that the hang up here is something that (to my knowledge) no wallet is handling properly, and that's the output distribution used to select decoys for each inputs ring. This distribution is ~10MB in size, and if uncached has to be pulled from the selected daemon the first time a transaction is sent after each sync.

Instead of this "just in time" output distribution pull, it would be a vastly superior UX for the output distribution to be cached the first time it is pulled, and then that cache appended to each subsequent sync to keep it up to date. This would make sending Monero *much* more responsive and reduce bandwidth requirements.

I also believe that this would significantly reduce the disk IO load on remote nodes that are popular, as pulling this list is quite an intensive random IOPS process as it has to grab them from all throughout the chain history.

**Comment by SamsungGalaxyPlayer** [comment]
Semi-related sanity checks on the output distribution to catch weak attempts at output poisoning by malicious nodes: https://github.com/feather-wallet/monero/commit/fdd5c639127a5163f739147341bc1b03f8d0a889

**Comment by sethforprivacy** [comment]
Leave it to tobtoht to get this fixed so quickly 🔥

Exciting it can be done easily in wallets, as everything downstream will now benefit.

**Comment by sethforprivacy** [comment]
While this might still be a helpful change, the core cause of the issues I was experiencing should be resolved once a Cake release containing https://github.com/monero-project/monero/pull/8408 is pushed.

I'm happy to alpha test that if you can get a build up with it.

**Comment by sethforprivacy** [comment]
> @sethforprivacy was the output caching specifically merged into wallet2?

No, just the DNS fixes -- I don't believe @tobtoht PR'd the output distribution change.

**Comment by SamsungGalaxyPlayer** [comment]
@sethforprivacy do you know if this wallet2 change was made?

**Comment by sethforprivacy** [comment]
Yes, all relevant changes were pushed a while ago (but were mostly related to DNS, not output caching).
