### ISSUE TITLE
Hive error issue

### ISSUE THREAD

**Issue by Leady420** [cake-tech/cake_wallet#420]
Hi,

I have been greeted with this message when I open the app.

please see attached
![88EBFFC8-982C-45E1-B5AE-2121DEAD4A23](https://user-images.githubusercontent.com/109663665/179959495-662baba8-548d-4ee8-a9cc-0453a5ba9327.png)

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/420

**Comment by SamsungGalaxyPlayer** [comment]
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet
