### ISSUE TITLE
When I switch to the BTC test network and then send tBTC, there are some errors.

### ISSUE THREAD

**Issue by coloredSky** [cake-tech/cake_wallet#438]
When I switch to the BTC test network and then send tBTC, there are some errors.

![WechatIMG506](https://user-images.githubusercontent.com/12792371/180912915-6ef8df1b-8225-416d-98fc-09765f7e9a5d.jpeg)

![WechatIMG505](https://user-images.githubusercontent.com/12792371/180912938-dd2dc845-e4b4-44fe-a46c-a06e0e672098.jpeg)

**Comment by SamsungGalaxyPlayer** [comment]
We don't support tBTC, at least not intentionally.

**Comment by coloredSky** [comment]
I switched BTC testNet in code bitcoin_wallet.dart and then replaced the node with the test site.
![WechatIMG509](https://user-images.githubusercontent.com/12792371/180933754-13745834-0e93-4837-915a-3c816165d0ec.jpeg)

**Comment by SamsungGalaxyPlayer** [comment]
We don't have plans to formally support Bitcoin testnet at this time.
