### ISSUE TITLE
[Feature Request] monero: set custom node as "Trusted" 

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#453]
Issue:
Upon each and every launch of the wallet, it downloads ~8.5mb of data from the connected node. Not good for those on slow connections or with limited data allotments. 

Asking moneromoo, I was made aware that using the flag --trusted-daemon will avoid the download.
The flag should, of course, only be used with nodes that you either run yourself or personally know and trust the operator. 

Request:
On the "add node" screen, the addition of a toggle for "trusted" or "I trust this node".
This toggle should connect to the node using the --trusted-daemon flag, thereby saving a fair amount of data and time when using the wallet with a trusted node. 

Pre-added nodes should not use the flag.

**Comment by SamsungGalaxyPlayer** [comment]
Resolved by https://github.com/cake-tech/cake_wallet/pull/529

**Comment by nahuhh** [comment]
Can confirm data savings on the release are as described
Thanks
