### ISSUE TITLE
Crash on Android 12 / Calyx 3.7.0

### ISSUE THREAD

**Issue by gringofe** [cake-tech/cake_wallet#460]
Hi,

when I launch Cake wallet on CalyxOS 3.7.0 (Android 12), the only thing I see is this error message:
![Screenshot_20220808-194047](https://user-images.githubusercontent.com/58902674/183480164-68d7061a-9faa-4b21-af10-614750704654.png)

**Comment by SamsungGalaxyPlayer** [comment]
Did you have an existing wallet? If you have the seed(s), please try wiping everything, uninstalling Cake Wallet, and then reinstalling.

**Comment by thestinger** [comment]
The exception doesn't indicate that it's a hardware issue but it's at least an OS or firmware bug not an app bug.

**Comment by thestinger** [comment]
The linked issue is about the Android 12 firmware not supporting Android 11 anymore. People who moved to the Android 12 Beta and then back to the stable release (Android 11) could not use hardware attestation via the secure element (Titan M). It isn't relevant to your issue.
