### ISSUE TITLE
[Feature request] Remove ability for Cake Pay and third parties to link gift card purchases

### ISSUE THREAD

**Issue by ChristopherKing42** [cake-tech/cake_wallet#471]
My understanding is that Cake Wallet leaks at least the following information to Cake Pay when making a purchase:

- IP Address
- Email Address

Although I think Cake Pay is a huge leap forward, it would be a vast improvement if gift card purchases couldn't be linked as coming from the same user, by default. (You could of course use multiple Cake Pay accounts to prevent them from linking, which I believe is allowed; it's not very convenient though.) With the ability for them to be linked, the privacy isn't actually much better than using a credit card company (but of course Cake Pay is in a much better position to inovate it's privacy).

As for IP, the user can and must use a VPN or similar to hide that, so not much Cake Wallet can do (I think?).

As for email, here's my suggestion: all communication (including receipts) are sent to the app instead of email. There could be an option to automatically save or email these transactions, but these would be done locally instead of by the Cake Pay server.

After this, I would suggest getting publishing an independent audit of the open source code to verify that the gift cards are no longer linkable, in case we're forgetting anything. (If it can't be verified based on the open source code, we'd need to take Cake Pay on their word that it's private.)

**Comment by SamsungGalaxyPlayer** [comment]
Sadly we need the ability to talk to a merchant somehow to get the gift cards, so there's no way to fully address your concerns. You need to get the gift card info initially somehow; it doesn't really matter if it's delivered by email or to the app by API.

Credit cards require SSN, name, physical address, and credit check to get, which is definitely more invasive than an email.

**Comment by ChristopherKing42** [comment]
@SamsungGalaxyPlayer 

> Sadly we need the ability to talk to a merchant somehow to get the gift cards

OH, that makes sense.

How about this then? Each time you buy a gift card a new email is randomly generated with a "cakepay.com" domain, which the app can access. As long as these emails can't be linked, this restores the unlinkable property. (This could be optional, in case someone really does want to control the email address.)
