### ISSUE TITLE
Updating Monero.com wallet to 1.0.9 erased all user settings including wallet file

### ISSUE THREAD

**Issue by MoneroArbo** [cake-tech/cake_wallet#473]
It just happened today when the update was finally pushed to my device from Google Play Store. OS is Android 11. Curiously, the same did NOT happen when I updated Cake Wallet to 4.4.4. If there's any other info or logs I can look for I'm happy to do that. This could also be an OS issue I suppose, but it's the first time I recall seeing an app have it's user data automatically cleared after an update.

I didn't lose any funds, so no worries there, but less careful users might.

**Comment by SamsungGalaxyPlayer** [comment]
@MoneroArbo can you provide all the device info you can, either here or to support@cakewallet.com? We're unable to reproduce.

**Comment by MoneroArbo** [comment]
phone model: oneplus kb2003

exact os: lineage_kebab-userdebug 11 RQ3A.211001.001 64b9fb7378

I haven't tried to reproduce it myself but let me see what I can do

**Comment by MoneroArbo** [comment]
phone model: oneplus kb2003

exact os: lineage_kebab-userdebug 11 RQ3A.211001.001 64b9fb7378

I tried to reproduce but I don't think I can install old versions in Google Play and if I install the apk it breaks updating through Google Play.

![Screenshot_Google_Play_Store](https://user-images.githubusercontent.com/65900302/184421353-0e0ccaff-a0b6-40d9-9af3-fdb29e352b51.png)

**Comment by MoneroArbo** [comment]
Friends and such seem to have updated with no issues so I'm going to go ahead and close this

**Comment by SamsungGalaxyPlayer** [comment]
If you can reproduce somehow, please let us know! We appreciate the report. Thanks for backing up your seed(s)!
