### ISSUE TITLE
[Feature Request] Option to use randomized cakepay.com email instead of providing your own

### ISSUE THREAD

**Issue by ChristopherKing42** [cake-tech/cake_wallet#474]
If I understand #471, an email is required to work with the gift card vendors. As a way to increase privacy, I propose an option for Cake Pay itself to provide the email. Each time you purchase a gift card, a random email account with domain cakepay.com would be created. This way the gift card purchases couldn't be linked.

**Comment by nahuhh** [comment]
Perhaps youre requesting "cake labs to create a new product for anonymous email"

**Comment by dginovker** [comment]
> Perhaps youre requesting "cake labs to create a new product for anonymous email"

I haven't verified the security, but there are existing temporary email APIs (others exist too): https://temp-mail.org/en/api

**Comment by ChristopherKing42** [comment]
Yeah, having Cake Pay automatically use something like that would be awesome! Cake Wallet already has a couple partners, why not one more?

**Comment by ChristopherKing42** [comment]
> I haven't verified the security, but there are existing temporary email APIs (others exist too): https://temp-mail.org/en/api

As far as I can tell, the security of the email is actually irrelevant: since Cake Wallet wouldn't be leaking any info, there's nothing the email provider could do to harm privacy (it can't leak secrets it doesn't even have). In addition, the actual gift card code is sent to the app, not the email, so they can't steal your gift cards.

**Comment by qvqc** [comment]
this could be accomplished by using a catch-all email address to a domain. most email providers have this feature if u are allowed a custom domain.  when a request for a giftcard is made by the user, cakepay could provide randomHash@cakepay.com to the giftcard api.  then check their catch all email address and process them with the receiver field randomHashs, greping the giftcards, and passing to the user

**Comment by SamsungGalaxyPlayer** [comment]
Closing this since we don't plan to make an email aliasing service. A lot of great privacy friends already have them :)
