### ISSUE TITLE
Bug: cakepay showing white screen 

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#476]
Steps to reproduce

1. Open cakepay
2. Tap filter button (hard to tap)
3. Press device's back button ¹
4. Tap filter again
Result:
White screen

¹ If in #3 you use the in app "X" button, no issues.

Ps. The x should probably be a ☑️

Android 10, cake 4.4.5

**Comment by SamsungGalaxyPlayer** [comment]
Will investigate.

**Comment by SamsungGalaxyPlayer** [comment]
@nahuhh is this resolved?

**Comment by nahuhh** [comment]
No longer experiencing this on 4.4.7. Closing.
