### ISSUE TITLE
CakeWallet Transaction Fee Questions

### ISSUE THREAD

**Issue by ACK-J** [cake-tech/cake_wallet#477]
I've recently been looking into the ways wallets calculate the base fee, and subsequent "priorities" for a transaction. The way Monero calculates base fees is complicated and poorly understood/documented. I fear varying fee structures could damage user privacy by further dividing people into smaller and smaller anonymity pools, as previously [shown by Isthmus](https://www.youtube.com/watch?v=XIrqyxU3k5Q). 
## Hardcoded Priority Fees
I came across some code in CakeWallet, which uses hardcoded fees. I was wondering if someone could explain:

1. What is the purpose of the hardcoded values?
2. Is this simply leftover code? Or is it currently being used by the application?

https://github.com/cake-tech/cake_wallet/blob/b72443a8c4f2fb50e34a7e5510afb52cf13f366d/cw_monero/lib/monero_wallet.dart#L233-L252

## Different Priority Levels
Secondly, I noticed that Cake uses 5 different "priority" levels, deviating from the monero-wallet-gui, which only has 4. As uniformity is Monero's biggest strength against on-chain heuristics, I was wondering if someone could comment further on how the priority levels are chosen within CakeWallet.

| | |
|:-------------------------:|:-------------------------:|
| <img width="500" alt="" src=https://user-images.githubusercontent.com/60232273/184518840-79e6db23-8c22-4131-a678-86f6285e8408.png>IOS CakeWallet Priority Levels|<img width="500" alt="" src="https://user-images.githubusercontent.com/60232273/184518899-b4b08819-2a0d-4d3d-936b-784c995af486.png">Monero-Wallet-GUI Priority Levels |

**Comment by SamsungGalaxyPlayer** [comment]
The fee ***estimates*** that are shown to the user are hardcode values. This can be improved, but fees are typically so low that it doesn't matter much in practice. It's a low priority improvement we have in the backlog.

We allow the same 5 fee options as the CLI. I believe "normal" = "default". We can harmonize the language; those have changed over time.

**Comment by ACK-J** [comment]
Okay I think I understand, so these values are just used for UX and an appropriate fee is calculated before the transaction is sent?

**Comment by SamsungGalaxyPlayer** [comment]
Yes, this is only for display.

**Comment by SamsungGalaxyPlayer** [comment]
https://guides.cakewallet.com/docs/monero/#monero-fee-levels
