### ISSUE TITLE
How to build for iOS？

### ISSUE THREAD

**Issue by coloredSky** [cake-tech/cake_wallet#479]
How to build for iOS？I didn't see the documentation.Could you point it out to me,thanks.

**Comment by emanuelb** [comment]
There is documentation in open MR at: https://github.com/cake-tech/cake_wallet/pull/213/files#diff-bd3037483c933283e8629c01582df685b47b5357b192e90151976bb07d3dc008

issue can be closed as it's duplicate, there older issues about iOS build instructions at: #207 and #114
