### ISSUE TITLE
[Feature Request] try to convince gift card provider to let you use daily resetting ID instead

### ISSUE THREAD

**Issue by ChristopherKing42** [cake-tech/cake_wallet#481]
According to https://www.reddit.com/r/Monero/comments/wpa19u/update_on_cake_pays_providers_requirement_of the reason Cake Pay will need to start leaking App IDs is because of a daily $10,000 limit.

Feature Request: since it's a daily limit, try to convince them to let you use a daily resetting ID instead. You could tell them that a persistent id *violates* the privacy principle of "data minimisation", but that you have a different kind of ID (the daily resetting one) that hopefully complies with that principle.

**Comment by SamsungGalaxyPlayer** [comment]
This isn't possible. There's no way to prevent spoofing while also allowing IDs that aren't associated with each other.
