### ISSUE TITLE
Hive Error on CAKE Walletq

### ISSUE THREAD

**Issue by CPCMikey** [cake-tech/cake_wallet#482]
Hello.  When I open my CAKE Wallet on iOS, I get the following message:

Error:
HiveError: This should not happen. Please open an issue on GitHub.

Anyone know what I can do to fix this?  I just want to access my XMR that I have store in CAKE Wallet.

Thanks for any help.

**Comment by SamsungGalaxyPlayer** [comment]
This is an issue with a Cake Wallet dependency that will take a lot of effort to fix. We're actively working on it, but it won't be fixed soon.

Please restore your funds from mnemonic seed. If you need help, email support@cakewallet.com

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet
