### ISSUE TITLE
[Bug] Exchange > coin search = inverted text color

### ISSUE THREAD

**Issue by nahuhh** [cake-tech/cake_wallet#488]
Issue only present on Dark Mode.
Light and bright modes seem unaffected.

![Image_229.jpg](https://user-images.githubusercontent.com/50635951/187043882-66937fbf-1e28-4bfb-be49-3c75c8889c9a.jpg)

Android 10 v4.4.5

**Comment by SamsungGalaxyPlayer** [comment]
Does this persist in 4.5.0?
