### ISSUE TITLE
cake wallet hive error

### ISSUE THREAD

**Issue by kojack223** [cake-tech/cake_wallet#489]
can not access my cake wallet. White screen that says.
ERROR:
This should not happen. Please open an issue on GitHub.
Can someone help?

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet
