### ISSUE TITLE
Cake fails to run on calyxOS

### ISSUE THREAD

**Issue by JeremiahSecrist** [cake-tech/cake_wallet#527]
This was running the latest version from github. The issue happens on both variants of cake. Let me know If you would like me to test versions or run tests.

![IMG_20221003_193820.jpg](https://user-images.githubusercontent.com/26032621/193704595-e6c39718-6faa-44f6-b761-cef7c88948c9.jpg)

![Screenshot_20221003-193557.png](https://user-images.githubusercontent.com/26032621/193704635-071283a6-7eda-4747-8d30-8dfde843d40e.png)

**Comment by SamsungGalaxyPlayer** [comment]
Can you please try with 4.5.0 and report back?

**Comment by arouzing** [comment]
> Can you please try with 4.5.0 and report back?
Calyxos has recently updated to a new version of android (13) it now works on this version. Sadly, I'm am unable to test if it would work on android 12. I'd image most calyx users to be good about updating.
