### ISSUE TITLE
FAIL to Sync Android 7  monero_com_1.1.1.apk 

### ISSUE THREAD

**Issue by juanpc2018** [cake-tech/cake_wallet#533]
Explodes / Crash, Returns to Block 0 "2million something."
Crash Again, Returns to Block 0.
impossible to Sync.

**Comment by SamsungGalaxyPlayer** [comment]
Device details? Is this an issue for XMR or other assets? Does it persist with other nodes on https://nodes.monero.com?

**Comment by juanpc2018** [comment]
https://www.gsmarena.com/lg_v10-7606.php

node.supportxmr.com
✅   All systems are operational

**Comment by juanpc2018** [comment]
What? 
Fails / crash also in Android 8
LG V20
https://www.gsmarena.com/lg_v20-8238.php
