### ISSUE TITLE
Accessibility: unlabeled buttons with talkback

### ISSUE THREAD

**Issue by davidbtc2009** [cake-tech/cake_wallet#536]
On the main wallet page the menu button and the "x" button on the "Introducing Cake Pay" are unlabeled when using talkback. On the PIN entry screen the delete button to the right of "0" is unlabeled.

**Comment by SamsungGalaxyPlayer** [comment]
Thanks! I'll make a note so we can fix.

**Comment by benhall847** [comment]
I think I can shed some light on this -

correct me if im wrong

But I have ran into this issue many times.

It seems if you are using a phone with a removable battery (or maybe simply a phone that runs out of battery)

If the phone is abruptly shut-off while the wallet is syncing - you will no longer be able to open the wallet
& are forced to restore the wallet from seed.

**Comment by shortwavesurfer2009** [comment]
@benhall847 i think you might have replied to the wrong issue as that has nothing to do wih this.

**Comment by benhall847** [comment]
ty sir fixed - it was ticket 637
idk how i got that mixed up
