### ISSUE TITLE
Profiles Use One Seed Phrase For All Wallets

### ISSUE THREAD

**Issue by trymeouteh** [cake-tech/cake_wallet#541]
I would like to purpose a different way to structure or the option to structure Cake Wallet different for the user. Most multi-profile and multi-coin wallets are structured as such, were you can choose which profile which could be a personal profile, work profile, etc. The profile stores the 12/24 seed phrase for all the wallets in the profile. Then you choose which account to use which be the crypto such as Bitcoin, Litecoin or Monero and the BIP44 account number (View https://iancoleman.io/bip39/ for more on BIP49 account number). Then you have your address with that wallet account.

This will require [12/24 seed phrase support](https://github.com/cake-tech/cake_wallet/issues/301) for all coins.

https://iancoleman.io/bip39/

- Profile (Personal) [wedding april weapon raven column feature mimic grant together husband panda skull]
   - Account (Bitcoin 0)
      - Address 0 [m/44'/0'/0'/0/0 13cQt5kjZdZ31z8qAoZ3hiLqpfzMmcmnhr]
      - Address 1 [m/44'/0'/0'/0/1 1PvaNJgkLrb3ATzMc1sgwg1vMeCHrEJmhA]
      - Address 2 [m/44'/0'/0'/0/2 1QFjifxns4fToUsWkDn4BwUsg42E4AyUs7]
      - Address 3 [m/44'/0'/0'/0/3 1H8PTatuSqj2kkJ8u9ia7DUNw89svAra7E]
      - Address 4 [m/44'/0'/0'/0/4 1N9bbwdX3EoRtNHwsV6do6zGXcdu4LyNkx]
   - Account (Bitcoin 1)
      - Address 0 [m/44'/0'/1'/0/0 1Fyu2SS9oLqKZZAGCW2taRQWKTWPWZvLhK]
      - Address 1 [m/44'/0'/1'/0/1 1LGyp6ZUrMwZ298uohzwtgj2sKvfJaTH4s]
      - Address 2 [m/44'/0'/1'/0/2 1Bk5U9iecLgbsm4YW9SRfPvxbb1qkyuV86]
   - Account (Litecoin 0)
      - Address 0 [m/44'/0'/0'/0/0 LRFsr1ePaaoSqcbTZ98pQ9q9f53FD6XXch]
      - Address 1 [m/44'/0'/0'/0/1 LVERJ8vxku9Z4rQqcAip41bsZGMzh1Up5A]
      - Address 2 [m/44'/0'/0'/0/2 LLPSSNoxhx7xaUewNSqG2bxwLFFZJvdrMF]
      - Address 3 [m/44'/0'/0'/0/3 LWwAALnt4y2tzgTF6LN1pf1msjYk3z8e6Q]
 - Profile (Work)
   - Account (Bitcoin 0) [town sand soldier method tone give pair smile pigeon school mind avocado]
      - Address 0 [m/44'/0'/0'/0/0 1HP7rJjLPFwbbep6aMPkvzmYNmaj9GnyQv]
      - Address 1 [m/44'/0'/0'/0/1 1AQjgxBqBNHTENGLoAd5169GT2NMtePDnu]
   - Account (Litecoin 0)
      - Address 0 [m/44'/0'/0'/0/0 LKHZp85t9iKh61aCYqHSkzZHSLByUaAbri]
      - Address 1 [m/44'/0'/0'/0/1 LUf3diUL7pAriq9n2vBuPCrd17JWqR9Ymo]
      - Address 2 [m/44'/0'/0'/0/2 LaeQ2d65PnjcMhJvVRSy4tj3jV55bmcPLT]
      - Address 3 [m/44'/0'/0'/0/3 LUR9fHQFHJNKNvhZAFcCzs3uLzqdLZvqGq]
      - Address 4 [m/44'/0'/0'/0/4 LWzomPYHVtZZUXfhvK8uUUeBScyu1CjBf2]

**Comment by SamsungGalaxyPlayer** [comment]
We do not currently plan to support a single seed for all wallets.
