### ISSUE TITLE
Hive Error - Cake Wallet - Iphone 'Error. Please contact Github'

### ISSUE THREAD

**Issue by starkmeister11** [cake-tech/cake_wallet#549]
Hi,

everytime I now open my Cake wallet it just comes up with a white screen with the message 'ERROR: HIVE ERROR. This should not happen. Please open an issue on Github'.

Anyone any ideas?

Much Appreciated.

**Comment by starkmeister11** [comment]
I also have only 24 of the 25 word mnemonic.

what a fool ive been.

**Comment by Forthelowitcango420** [comment]
Did you resolve the issue somehow?

**Comment by SamsungGalaxyPlayer** [comment]
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet
