### ISSUE TITLE
Accessibility: low contrast.

### ISSUE THREAD

**Issue by davidbtc2009** [cake-tech/cake_wallet#563]
On the "Bright" theme the white text on that bright blue/magenta background is really hard to read. 

In the "light" theme the text is easy enough to read, but the bubbles showing your balance and "introducing Cake Pay are difficult to distinguish from the white background. The action bar for buy, receive, exchange, send, and sell is also this way.

![Screenshot_20221024-151204_Cake_Wallet](https://user-images.githubusercontent.com/67274571/197607440-b96e63ca-dd68-4877-ac22-33aed826ab40.png)

![Screenshot_20221024-151230_Cake_Wallet](https://user-images.githubusercontent.com/67274571/197607516-f1d207c8-f93d-4d2f-9df2-884a378c4d2d.png)

![Screenshot_20221024-151220_Cake_Wallet_1](https://user-images.githubusercontent.com/67274571/197607543-cbfa8899-c4f4-4c0d-9550-c3c2a85616a2.png)

![Screenshot_20221024-151156_Cake_Wallet_1](https://user-images.githubusercontent.com/67274571/197607580-7339f5f6-c518-4814-af07-3e59a51239e0.png)

**Comment by davidbtc2009** [comment]
Here is another example. See the red text below the address box?
![Screenshot_20221110-083013_Monero com_1](https://user-images.githubusercontent.com/67274571/201106171-2a582361-b12f-45d7-8c67-9b888cdda8c8.png)

**Comment by davidbtc2009** [comment]
Another screenshot. See the error below the address is hard to see
![Screenshot_20221110-083013_Monero com_1_1](https://user-images.githubusercontent.com/67274571/201119812-b319196e-a147-4519-968d-873e5e939191.png)

**Comment by tuxpizza** [comment]
Closing since we have many themes that have much better contrast now
