### ISSUE TITLE
Add wallet and contact sort options

### ISSUE THREAD

**Issue by trymeouteh** [cake-tech/cake_wallet#618]
Sort wallets and contacts in the address by the wallet name under My Wallets and by the contact name under Contacts.

**Comment by SamsungGalaxyPlayer** [comment]
Wallets portion potentially conflicts with #617 

Sort by:

1. Index (current; for wallet)
2. Name

**Comment by trymeouteh** [comment]
> Wallets portion potentially conflicts with #617

Not unless wallets are sorted by name with accounts and labels sorted by name and are within the wallets

```
A (Wallet)
- A (Account)
   - 0 (Label)
- B (Account)
   - A (Label)
   - B (Label)
B (Wallet)
- B (Account)
   - 0 (Label)
```
