### ISSUE TITLE
Cake Pay Open Source Code Base?

### ISSUE THREAD

**Issue by itsMikeLowrey** [cake-tech/cake_wallet#635]
Hi,
I know that this is the repo for the cake_wallet app, but I was not able to find any mention of cake pay from a quick search in this repo. Cake wallet appears to be open source, but cake pay does not seem to be open source. I think they are both built and deployed in the same app on the google play store though. Does that mean that when I download cake wallet from google play store, only a portion of the downloaded app is open source and some portion is closed source? I don't want to make any assumptions or anything so I thought I would ask here for some clarity. Thanks for your time.

**Comment by SamsungGalaxyPlayer** [comment]
Thanks for your question! The app you download is open source, including the interactions with third-party services like Cake Pay servers. However, the server code that runs Cake Pay on the back-end is not open source.

Here is some related open source code that shows how the app interacts with the Cake Pay servers:

https://github.com/cake-tech/cake_wallet/tree/main/lib/ionia

**Comment by itsMikeLowrey** [comment]
Thank you so much.
