### ISSUE TITLE
Automatically choose random public node

### ISSUE THREAD

**Issue by SisyphusRising** [cake-tech/cake_wallet#638]
Electrum and Feather Wallet have a list of public nodes and one is randomly chosen to connect to when the application is opened.

With Cake Wallet you select a public node and it doesn't change unless you manually do it.

To minimize trust in a single public node, it would be nice to have the option to automatically and randomly select from the public node list every time the app is opened.

**Comment by SamsungGalaxyPlayer** [comment]
In Cake Wallet, users connect to our nodes by default instead of random public nodes. We consider this experience preferable to connecting to random remote nodes, which could have privacy drawbacks if operated by attackers. Of course, users should use got own nodes.
