### ISSUE TITLE
New wallet restore from backup file does not allow for 6-digit pin code, making wallet unusable.

### ISSUE THREAD

**Issue by Efocat** [cake-tech/cake_wallet#639]
Restoring the app set up with 6-digits PIN to a new device using the backup file method will default the new wallet to 4-digits PIN, accounts are restored successfully but any action requiring a PIN becomes impossible , essentially making the new wallet unusable using this method.

Steps to reproduce:
1. set up cake wallet with 6-digit pin code
2. export backup file
3. restore wallet from backup file on a separate device with fresh install of cake wallet
4. attempt actions requiring a PIN (change PIN, close&reopen app, etc.)

**Comment by SamsungGalaxyPlayer** [comment]
I can reproduce. Working on it.
