### ISSUE TITLE
"Pocket change" template to split balance utxos

### ISSUE THREAD

**Issue by d-Martian** [cake-tech/cake_wallet#661]
To avoid 10 confirmation (20 minute) locked balances, it's useful to have a wallet with multiple, smaller utxo's. To do so, people send themselves their own wallet balance consisting of one or a few uxtos, in smaller denominations.

Cake Wallet already has the function to send to multiple addresses, and to quickly perform preset transactions using templates, but there isn't a way to use these functions to send oneself their balance in smaller denominations that can help prevent large balances from being locked for 10 confirmations.

This is a feature request to add a template or make it possible to easily create templates that perform the aforementioned balance dividing functionality.

**Comment by SamsungGalaxyPlayer** [comment]
With 4.8.0 and higher, you can make a Send template for the amounts you need with multiple recipients, for example 10 recipients of $10.

https://github.com/cake-tech/cake_wallet/releases/tag/v4.8.0
