### ISSUE TITLE
Cannot sign into Wallet after update.

### ISSUE THREAD

**Issue by CyberNomadic** [cake-tech/cake_wallet#672]
So essentially what occurs is when typing in the pin, a white blip appears that just says "Authentication" and the app never signs in. 
![Screenshot_2022-12-14-17-14-23-04_d1faba4888427a9c33a26f7ff96cac9c](https://user-images.githubusercontent.com/11414210/207726669-da286844-97f2-41ec-a530-eb1c7ac810fd.jpg)

**Comment by SamsungGalaxyPlayer** [comment]
Did you get the APK on GitHub, did you get this from Google Play, or did you get this from the App Store?

**Comment by SamsungGalaxyPlayer** [comment]
@CyberNomadic please try downloading the APK from releases again. Please re-open this issue if you still have issues. Thanks!
