### ISSUE TITLE
[$150 Bounty] Add Hausa (ha/hau)

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [cake-tech/cake_wallet#708]
Please see the steps here on how to add the language:

https://github.com/cake-tech/cake_wallet#add-a-new-language

The following conditions apply:

* You may start with a machine translation, but you must review the changes and make modifications where necessary. Some strings require knowledge of context in the wallet.
* Bounties are paid in XMR.
* You must sign a consulting agreement with Cake and provide your name if you complete more than 1 translation. Email justin@cakewallet.com for this.
* Reference this issue in your pull request.
* You must reply to this issue indicating that you will work on it. This will reserve the bounty for 1 week. After 1 week, another person may reserve this bounty.
* You will submit a pull request of your own work and sign any/all copyrights over to Cake Labs LLC with no restrictions.
* You must not be an existing or past Cake employee (without prior approval).
* The bounty will only be paid after the pull request is merged. Cake reserves the right to close pull requests and to not pay a bounty for any reason.
* This is separate from [Monero Bounties](https://bounties.monero.social/) and any other similar program. If another program covers this same work, you'll need to work with the other system administrators for their own programs. If anyone wishes to further incentivize this work, we recommend they use a system like [Monero Bounties](https://bounties.monero.social/) and comment the relevant bounty link below.
* If you have questions about this bounty (eg: scope of work), please comment below.

If you wish to reserve this bounty, please reply with:

> I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by Justxd22** [comment]
I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by SamsungGalaxyPlayer** [comment]
@Justxd22 please provide your XMR address here or email it to justin@cakewallet.com
