### ISSUE TITLE
Wallet coin stolen

### ISSUE THREAD

**Issue by lovejiya0213** [cake-tech/cake_wallet#734]
The Monero wallet received by swapping Bitcoin was not checked, so I put 25 passwords into the cake wallet and synchronized it. But as soon as it was synchronized, my coin was transferred elsewhere.I didn't send money, is there any way I can find it again? Maybe the thief knows the code 25.!
Synchronized time is 23.01.17 pm22:23
[image](https://user-images.githubusercontent.com/122940718/213076213-f5f57f31-d40d-410d-9a88-e25736364339.png)

**Comment by Justxd22** [comment]
@lovejiya0213 you will get better support on telegram lookup cake wallet group

**Comment by lovejiya0213** [comment]
> @lovejiya0213 you will get better support on telegram lookup cake wallet group

Tell me your Telegram ID.

**Comment by lovejiya0213** [comment]
> @lovejiya0213 you will get better support on telegram lookup cake wallet group

The first Monero wallet manager contacted me, so I can't answer this question, right? The first one I used, Monero, pretending to be the wallet manager, I don't trust this manager.

![image](https://user-images.githubusercontent.com/122940718/213081453-e253c2d7-a4b0-4ad0-a271-15fbf37ddbce.png)

**Comment by Justxd22** [comment]
@lovejiya0213 no, you look for their official verified group

**Comment by lovejiya0213** [comment]
>  no, you look for their official verified group

Then what am I supposed to do?

**Comment by Justxd22** [comment]
@lovejiya0213 don't reply to that screenshot it's a scam, and never give your seed, only contact verfied cake wallet 
![Screenshot_20230118-061446_Nekogram](https://user-images.githubusercontent.com/66136622/213082402-fa46f6fe-1fc8-4584-9d71-e28349142242.png)

**Comment by SamsungGalaxyPlayer** [comment]
@lovejiya0213 the screenshot you sent is a SCAM! 

Only contact @cakewallet_bot on Telegram. NO OTHER ACCOUNT!
