### ISSUE TITLE
Incorrect fiat balance in Android app

### ISSUE THREAD

**Issue by meyou69** [cake-tech/cake_wallet#795]
Hello,

I noticed that my current version of the Android app (version 4.5.6) has a bug where, when displaying my Monero wallet balance, it shows a balance which is not consistent with the fiat balance shown right under it.

The fiat currency chosen by me is Romanian RON. When I go to Google and manually convert my XMR balance to RON, the amount calculated is very different (way higher) than the one shown in the Cake Wallet.

This looks like a simple exchange rate bug. Can you look into it, please?

**Comment by SamsungGalaxyPlayer** [comment]
Hello, thanks for reporting this! We will look into the issue, and we should push an update to our API later this week.

**Comment by tannerdsilva** [comment]
Hello.

Your client is requesting a quote from XMR to RON, which is not a pair that exists directly on exchanges.

I cannot answer to what goes into the numbers you pull up in your Google searches, but I can tell you what market data we use to produce this rate for you.

Your XMR / RON quote is broken into two sub-queries....

1. Convert XMR to BTC. This price to BTC is averaged from many providers and we know this is accurate.

2. Convert the BTC price to RON. This pair is exchanged only on Binance.

By all means, my system is producing "expected" rates for both XMR / BTC and BTC / RON. And these prices are driven by real market volume on real exchanges.

Perhaps Google searches are more approximate than the data we are sourcing.

**Comment by tannerdsilva** [comment]
@SamsungGalaxyPlayer this issue is unrelated to developments in pricedb `v1.1` because Binance actively exchanges RON on their platform.

**Comment by tannerdsilva** [comment]
You are asking for a pair (XMR / RON) that does not directly exist on exchanges. So your request must be translated with a common currency. When picking a common currency, the highest volume route is chosen.

RON is traded only on OKX and Binance, against USDT and BTC.

Binance is facilitating BTC / RON with roughly $138K volume.
OKX is facilitating RON / USDT with roughly $175K in volume.

USDT is chosen for pricing in this case, since OKX is moving more volume.

So, to produce your XMR / RON price, we must...

1. Convert the XMR into USDT based on averages from many exchanges.

2. Convert the USDT to RON based on the rate on OKX.

_**Unfortunately:**_ it seems like OKX is trading RON / USDT at a rate that is _dramatically_ out of "the market rate". I'm not sure what exactly is going on with that price.

**Comment by tannerdsilva** [comment]
Does anyone have a guess as to why OKX's pricing for RON is so far out of line? RON / USDT is literally 4x higher price than what it should be.

**Comment by tannerdsilva** [comment]
Thank you @meyou69 for bringing this to our attention. I found a few very subtle flaws in the logic needed to produce this particular quote.

After making (and then deleting) two invalid response, I believe I finally have the issue nailed down.

Our service is now quoting XMR / RON at a much more reasonable rate, and I will be closing this ticket.

Thanks again.

**Comment by tannerdsilva** [comment]
I am actually going to reopen this issue because OKX is still trading RON / USDT at a super wacky rate (seemingly) and I am not going to be able to solve for that.

**Comment by tannerdsilva** [comment]
Aside from the bugs I have resolved, this is a primary reason the price continues to be incorrect.

https://www.okx.com/trade-spot/ron-usdt

**Comment by tannerdsilva** [comment]
I am exploring a possible adjustment to my algorithm that will direct the pricing outcome away from this fluke OKX pricing phenomena we are seemingly dealing with.

Not willing to hard-code anything for this particular use-case but I believe I might be able to tweak some conditions around this.

Will continue to post updates.

**Comment by SamsungGalaxyPlayer** [comment]
Found the issue. OKX has a market for RON that's for some silly other "Ronin" coin. Name overlap. Will fix :)

**Comment by tannerdsilva** [comment]
Thank you, Justin. Great find.

Blacklist applied in production, pricing for XMR / RON now reflective of general market quotes.

**Comment by SamsungGalaxyPlayer** [comment]
@meyou69 this should work now, thanks for reporting!

**Comment by meyou69** [comment]
I can confirm that the bug doesn't exist for me, anymore.
Thank you for fixing this!
