### ISSUE TITLE
Display notice when trying to delete active wallet

### ISSUE THREAD

**Issue by spoolUnabashed** [cake-tech/cake_wallet#806]
On the Wallets screen, if you try to swipe to delete a wallet entry, you cannot delete the active wallet that you are currently using. I had to do a search online to find this out.

Ideally, if there were greyed out button, that if clicked, displayed a notice with an explanation to switch to another wallet before trying to delete the current one, that would be preferable.

Additionally, it might be good to have the red delete icon appear when long pressing a wallet entry, and not just sliding to reveal it, however this might need to be opened in it's own issue.

**Comment by Juan-1405** [comment]
I might do this issue in the next couple of days.
