### ISSUE TITLE
Cake Pay Mobile: "Exception: Unexpected response http code: 400"

### ISSUE THREAD

**Issue by alt4weirdXMRaddress** [cake-tech/cake_wallet#842]
Cake Pay Mobile returns this error when attempting to buy a gift card from any store for any amount using XMR. Multiple wallet versions (Cakewallet 4.6.1 and Cakewallet 4.5.6), multiple connection methods (normal, VPN, Tor), multiple Monero nodes were tested. The error occurs using iOS and XMR; I have not tested for other platforms or currencies.
![image](https://user-images.githubusercontent.com/104111764/226762158-1f2e030a-46f8-4b01-8373-5e02b5636fa3.png)

**Comment by Sorsnce** [comment]
getting the same error..... this is happening on all vendors.... makes Cake Pay pretty much useless....
