### ISSUE TITLE
Displaying fiat balances does not work for CZK

### ISSUE THREAD

**Issue by holecekp** [cake-tech/cake_wallet#845]
Displaying balances does not work for the CZK currency. It used to work in the past but now "CZK 0.00" is always displayed instead. I am using version 4.6.1

Steps to reproduce:
1. Select in the menu: Display settings / Currency and set CZK
2. You can see that the balance in BTC, LTC and XMR is displayed correctly, but the fiat balance is not calculated correctly. "CZK 0.00" is displayed instead.
3. Select in the menu: Display settings / Currency and set for example EUR.
4. You can check that the fiat balance in EUR is dislayed. It seems that there is a problem only with CZK.

**Comment by holecekp** [comment]
I have written to Cake Wallet support mail and the problem has been fixed (https://status.cakewallet.com/incident/76).

**Comment by DeeDeeRanged** [comment]
Please re-open this issue as it does not work any more on Cake-Wallet 4.6.2 on Android.

**Comment by holecekp** [comment]
I can confirm that displaying fiat in CZK did not work a few hours ago. However, I have tried it now and it seems to work again.

**Comment by DeeDeeRanged** [comment]
Just checked and can confirm it works again, so issue is solved.
