### ISSUE TITLE
Split the repo

### ISSUE THREAD

**Issue by dukethorion** [cake-tech/cake_wallet#852]
Using Obtainium to update apps directly from Github.  Cake Wallet full and Monero.com Wallet being in the same repo leads to version mismatches.

IE:   
Installed version (1.3.1) - Monero.com apk

Update available: 4.6.1 (not Monero apk)

Possible to split the repository so these are treated as separate apps?

**Comment by SamsungGalaxyPlayer** [comment]
This will be sufficiently addressed with our own F-Droid repo, right?
