### ISSUE TITLE
Bitcoin transaction history frozen

### ISSUE THREAD

**Issue by saraelsa** [cake-tech/cake_wallet#897]
Ever since one particular Bitcoin transaction I received (multiple outputs if that makes any difference), my transaction history on Bitcoin is frozen. My sends since then keep showing up as pending (it's been over a month) whereas they've already been confirmed thoroughly on the blockchain. I can't see any receives in the history either.

The amount shows up just fine (including the unconfirmed/total values), it's just the transaction history that's bugged.

**Comment by SamsungGalaxyPlayer** [comment]
Does this issue persist?

**Comment by saraelsa** [comment]
No, it has fixed itself a while back.
