### ISSUE TITLE
15 security vendors and no sandboxes flagged this file as malicious (virustotal)

### ISSUE THREAD

**Issue by safarifox** [cake-tech/cake_wallet#996]
15 security vendors and no sandboxes flagged this file as malicious .
Virustotal detect apk as a virus
https://www.virustotal.com/gui/file/4227ef3dcc6d2f65b0bbfd4b8ce8e0f3465d06dcfb9678cea6d02678d2568c97

 RiskWare:Linux/BitCoinMiner.80a6289d
Antiy-AVL
RiskWare[RiskTool]/Linux.BitCoinMiner.bi
Arcabit
Application.Linux.Generic.D3955 [many]
Avast
ELF:Miner-JP [PUP]
Avast-Mobile
ELF:Miner-KA [PUP]
AVG
ELF:Miner-JP [PUP]
BitDefender
Application.Linux.Generic.14677
Fortinet
Riskware/Application
GData
Application.Linux.Generic.14680
Kaspersky
Not-a-virus:HEUR:RiskTool.Linux.BitCoinMiner.bi
MAX
Malware (ai Score=83)
McAfee-GW-Edition
Artemis
Trellix (FireEye)
Application.Linux.Generic.14677
VIPRE
Application.Linux.Generic.14677
ZoneAlarm by Check Point
Not-a-virus:HEUR:RiskTool.Linux.BitCoinMi

**Comment by SamsungGalaxyPlayer** [comment]
It's related to the Monero code. It's a false positive.
